### 1 :  Write a python program to display all the header tags from ‘en.wikipedia.org/wiki/Main_Page’.

In [213]:
import requests
from bs4 import BeautifulSoup

In [214]:
wiki_page = requests.get(' http://en.wikipedia.org/wiki/Main_Page?')

In [215]:
wiki_page

In [216]:
print('Status Code of the Website is ',wiki_page.status_code)

Status Code of the Website is  200

In [217]:
wiki_page.content

b'<!DOCTYPE html>\n<html class="client-nojs" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8"/>\n<title>Wikipedia, the free encyclopedia</title>\n<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"1c0f8e40-1fd1-4a50-bcdf-d3d03725c40a","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Main_Page","wgTitle":"Main Page","wgCurRevisionId":1004593520,"wgRevisionId":1004593520,"wgArticleId":15580374,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Main_Page","wgRelevantArticleId":15580374,"wgIsProbablyEditable":!1,"wgRelevantPageIsProbablyEditable":!1,"wgRestrictionEdit":["sysop"],"wgRestrictionMove":["sysop"],"wgIsMainPage":!0,"wgFlaggedRevsParams":{\n"tags":{"status":{"levels":-1}}},"wgMediaViewerOnClick":!0,"wgMediaViewerEnabledByDefault":!0,"wgPopupsFlags":10,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":!0,"nearby":!0,"watchlist":!0,"tagline":!1},"wgWMESchemaEditAttemptStepOversample":!1,"wgULSCurrentAutonym":"English","wgNoticeProject":"wikipedia","wgCentralAuthMobileDomain":!1,"wgEditSubmitButtonLabelPublish":!0,"wgULSPosition":"interlanguage","wgGENewcomerTasksGuidanceEnabled":!0,"wgGEAskQuestionEnabled":!1,"wgGELinkRecommendationsFrontendEnabled":!1,"wgWikibaseItemId":"Q5296"};RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","noscript":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","skins.vector.styles.legacy":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","ext.wikimediaBadges":\n"ready"};RLPAGEMODULES=["site","mediawiki.page.ready","skins.vector.legacy.js","ext.gadget.ReferenceTooltips","ext.gadget.charinsert","ext.gadget.extra-toolbar-buttons","ext.gadget.refToolbar","ext.gadget.switcher","ext.centralauth.centralautologin","mmv.head","mmv.bootstrap.autostart","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.growthExperiments.SuggestedEditSession"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.implement("user.options@1hzgi",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});\n});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cskins.vector.styles.legacy&amp;only=styles&amp;skin=vector"/>\n<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector"></script>\n<meta name="ResourceLoaderDynamicStyles" content=""/>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector"/>\n<meta name="generator" content="MediaWiki 1.37.0-wmf.7"/>\n<meta name="referrer" content="origin"/>\n<meta name="referrer" content="origin-when-crossorigin"/>\n<meta name="referrer" content="origin-when-cross-origin"/>\n<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/2/2a/Vicki_Cole.jpg"/>\n<meta property="og:title" content="Wikipedia, the free encyclopedia"/>\n<meta property="og:type" content="website"/>\n<link rel="preconnect" href="//upload.wikimedia.org"/>\n<link rel="alternate" media="only screen and (max-width: 720px)" href="//en.m.wikipedia.org/wiki/Main_Page"/>\n<link rel="alternate" type="application/atom+xml" title="Wikipedia picture of the day feed" href="/w/api.php?action=featuredfeed&amp;feed=potd&amp;feedformat=atom"/>\n<link rel="alternate" type="application/atom+xml" title="Wikipedia featured articles feed" href="/w/api.php?action=featuredfeed&amp;feed=featured&amp;feedformat=atom"/>\n<link rel="alternate" type="application/atom+xml" title="Wikipedia &quot;On this day...&quot; feed" href="/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom"/>\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png"/>\n<link rel="shortcut icon" href="/static/favicon/wikipedia.ico"/>\n<link rel="search" type="application/opensearchdescription+xml" href="/w/opensearch_desc.php" title="Wikipedia (en)"/>\n<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd"/>\n<link rel="license" href="//creativecommons.org/licenses/by-sa/3.0/"/>\n<link rel="canonical" href="https://en.wikipedia.org/wiki/Main_Page"/>\n<link rel="dns-prefetch" href="//login.wikimedia.org"/>\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n</head>\n<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Main_Page rootpage-Main_Page skin-vector action-view skin-vector-legacy"><div id="mw-page-base" class="noprint"></div>\n<div id="mw-head-base" class="noprint"></div>\n<div id="content" class="mw-body" role="main">\n\t<a id="top"></a>\n\t<div id="siteNotice"><!-- CentralNotice --></div>\n\t<div class="mw-indicators">\n\t</div>\n\t<h1 id="firstHeading" class="firstHeading" >Main Page</h1>\n\t<div id="bodyContent" class="vector-body">\n\t\t<div id="siteSub" class="noprint">From Wikipedia, the free encyclopedia</div>\n\t\t<div id="contentSub"></div>\n\t\t<div id="contentSub2"></div>\n\t\t\n\t\t<div id="jump-to-nav"></div>\n\t\t<a class="mw-jump-link" href="#mw-head">Jump to navigation</a>\n\t\t<a class="mw-jump-link" href="#searchInput">Jump to search</a>\n\t\t<div id="mw-content-text" class="mw-body-content mw-content-ltr" lang="en" dir="ltr"><div class="mw-parser-output"><style data-mw-deduplicate="TemplateStyles:r1004580458">.mw-parser-output #mp-topbanner{position:relative;box-sizing:border-box;min-width:47em;border-color:#ddd;background-color:#f9f9f9;white-space:nowrap}.mw-parser-output .mp-bordered,.mw-parser-output .mp-h2,body.skin-timeless .mw-parser-output .mp-h2{border-width:1px;border-style:solid}.mw-parser-output #mp-topbanner,.mw-parser-output .mp-h2,.mw-parser-output #mp-left{color:#000}.mw-parser-output #mp-welcomecount{margin:0.4em;width:22em;text-align:center}.mw-parser-output #mp-welcome{font-size:162%;padding:0.1em}.mw-parser-output #mp-free{font-size:95%}.mw-parser-output #articlecount{font-size:85%}.mw-parser-output #mp-portals{position:absolute;right:-1em;top:50%;margin-top:-2.4em;width:38%;min-width:25em;font-size:95%}.mw-parser-output #mp-portals li{position:absolute;left:0;top:0}.mw-parser-output #mp-portals .portal-hmid{left:33%}.mw-parser-output #mp-portals .portal-hright{left:66%}.mw-parser-output #mp-portals .portal-vmid{top:1.6em}.mw-parser-output #mp-portals .portal-vbot{top:3.2em}.mw-parser-output #mp-portals li:last-child{font-weight:bold}.mw-parser-output #mp-banner{margin-top:4px;padding:0.5em;background-color:#fffaf5;border-color:#f2e0ce}.mw-parser-output .mp-h2,body.skin-timeless .mw-parser-output .mp-h2{margin:0.5em;padding:0.2em 0.4em;font-size:120%;font-weight:bold;font-family:inherit}.mw-parser-output h2.mp-h2::after{border:none}.mw-parser-output .mp-later{font-size:85%;font-weight:normal}.mw-parser-output #mp-upper{width:100%;margin-top:4px;margin-bottom:0;border-spacing:0;border-collapse:separate}.mw-parser-output #mp-upper .mid-table{border-color:transparent}.mw-parser-output #mp-left{width:55%;border-color:#cef2e0;background:#f5fffa}.mw-parser-output #mp-right{width:45%;border-color:#cedff2;background:#f5faff}.mw-parser-output #mp-left,.mw-parser-output #mp-right{padding:0;vertical-align:top}.mw-parser-output #mp-left .mp-h2{background:#cef2e0;border-color:#a3bfb1}.mw-parser-output #mp-right .mp-h2{background:#cedff2;border-color:#a3b0bf}.mw-parser-output #mp-tfa,.mw-parser-output #mp-dyk,.mw-parser-output #mp-itn,.mw-parser-output #mp-otd,.mw-parser-output #mp-other-lower>div{padding:0.1em 0.6em}.mw-parser-output #mp-dyk-h2,.mw-parser-output #mp-otd-h2{clear:both}.mw-parser-output #mp-middle{margin-top:4px;border-color:#f2cedd;background:#fff5fa}.mw-parser-output #mp-middle,.mw-parser-output #mp-lower,.mw-parser-output #mp-other-lower{overflow:auto}.mw-parser-output #mp-tfl-h2{background:#f2cedd;border-color:#bfa3af}.mw-parser-output #mp-tfl{padding:0.3em 0.7em}.mw-parser-output #mp-lower{margin-top:4px;border-color:#ddcef2;background:#faf5ff}.mw-parser-output #mp-tfp-h2{background:#ddcef2;border-color:#afa3bf}.mw-parser-output #mp-tfp{margin:0.1em 0.4em 0.6em}.mw-parser-output #mp-other-lower{padding:0;border-color:#e2e2e2;margin-top:4px}.mw-parser-output #mp-dyk,.mw-parser-output #mp-otd,.mw-parser-output #mp-other-lower{padding-bottom:0.5em}.mw-parser-output #mp-other-lower .mp-h2{background:#eee;border-color:#ddd;color:#222}@media(max-width:875px){body.skin--responsive .mw-parser-output #mp-welcomecount{width:auto}body.skin--responsive .mw-parser-output #mp-topbanner{min-width:0;white-space:normal}body.skin--responsive .mw-parser-output #mp-portals{position:static;width:auto;min-width:0;text-align:center;border-top:1px solid #ddd;padding:0.4em 0;margin:0 0.4em}body.skin--responsive .mw-parser-output #mp-portals li{position:static;display:inline;padding:0 5px;white-space:nowrap}body.skin--responsive .mw-parser-output table,body.skin--responsive .mw-parser-output tr,body.skin--responsive .mw-parser-output td,body.skin--responsive .mw-parser-output tbody{display:block!important;width:100%!important;box-sizing:border-box}body.skin--responsive .mw-parser-output #mp-tfp tr:first-child td:first-child a{text-align:center;display:table;margin:0 auto}}</style>\n<div id="mp-topbanner" class="mp-bordered">\n<div id="mp-welcomecount">\n<div id="mp-welcome">Welcome to <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a>,</div>\n<div id="mp-free">the <a href="/wiki/Free_content" title="Free content">free</a> <a href="/wiki/Encyclopedia" title="Encyclopedia">encyclopedia</a> that <a href="/wiki/Help:Introduction_to_Wikipedia" title="Help:Introduction to Wikipedia">anyone can edit</a>.</div>\n<div id="articlecount"><a href="/wiki/Special:Statistics" title="Special:Statistics">6,310,260</a> articles in <a href="/wiki/English_language" title="English language">English</a></div>\n</div>\n<ul id="mp-portals">\n<li><a href="/wiki/Portal:The_arts" title="Portal:The arts">The arts</a></li>\n<li class="portal-vmid"><a href="/wiki/Portal:Biography" title="Portal:Biography">Biography</a></li>\n<li class="portal-vbot"><a href="/wiki/Portal:Geography" title="Portal:Geography">Geography</a></li>\n<li class="portal-hmid"><a href="/wiki/Portal:History" title="Portal:History">History</a></li>\n<li class="portal-hmid portal-vmid"><a href="/wiki/Portal:Mathematics" title="Portal:Mathematics">Mathematics</a></li>\n<li class="portal-hmid portal-vbot"><a href="/wiki/Portal:Science" title="Portal:Science">Science</a></li>\n<li class="portal-hright"><a href="/wiki/Portal:Society" title="Portal:Society">Society</a></li>\n<li class="portal-hright portal-vmid"><a href="/wiki/Portal:Technology" title="Portal:Technology">Technology</a></li>\n<li class="portal-hright portal-vbot"><a href="/wiki/Wikipedia:Contents/Portals" title="Wikipedia:Contents/Portals">All portals</a></li>\n</ul>\n</div>\n<table role="presentation" id="mp-upper">\n<tbody><tr>\n<td id="mp-left" class="MainPageBG mp-bordered">\n<h2 id="mp-tfa-h2" class="mp-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today\'s_featured_article">From today\'s featured article</span></h2>\n<div id="mp-tfa"><div id="mp-tfa-img" style="float: left; margin: 0.5em 0.9em 0.4em 0em;">\n<div class="thumbinner mp-thumb" style="background: transparent; border: none; padding: 0; max-width: 162px;">\n<a href="/wiki/File:Vicki_Cole.jpg" class="image" title="Cole with a recreation of her sign at the 1969 inaugural parade"><img alt="Cole with a recreation of her sign at the 1969 inaugural parade" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Vicki_Cole.jpg/162px-Vicki_Cole.jpg" decoding="async" width="162" height="122" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Vicki_Cole.jpg/243px-Vicki_Cole.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Vicki_Cole.jpg/324px-Vicki_Cole.jpg 2x" data-file-width="720" data-file-height="540" /></a><div class="thumbcaption" style="padding: 0.25em 0; word-wrap: break-word;">Cole with a recreation of her sign at the 1969 inaugural parade</div></div>\n</div>\n<p>"<b><a href="/wiki/Bring_Us_Together" title="Bring Us Together">Bring Us Together</a></b>" was a <a href="/wiki/List_of_political_slogans" title="List of political slogans">political slogan</a> popularized after the election of <a href="/wiki/Republican_Party_(United_States)" title="Republican Party (United States)">Republican</a> candidate <a href="/wiki/Richard_Nixon" title="Richard Nixon">Richard Nixon</a> as <a href="/wiki/President_of_the_United_States" title="President of the United States">President of the United States</a> in <a href="/wiki/1968_United_States_presidential_election" title="1968 United States presidential election">the 1968 election</a>. The text was derived from a sign that 13-year-old Vicki Lynne Cole stated that she had carried at Nixon\'s rally in her home town of <a href="/wiki/Deshler,_Ohio" title="Deshler, Ohio">Deshler, Ohio</a>, during the campaign. After being told of the sign, Nixon\'s speechwriters, including <a href="/wiki/William_Safire" title="William Safire">William Safire</a>, began inserting the phrase into his speeches. Nixon mentioned the rally sign in his victory speech, adopting the phrase as representing his administration\'s initial goal\xe2\x80\x94to reunify the bitterly divided country. Nixon invited Cole and her family to <a href="/wiki/First_inauguration_of_Richard_Nixon" title="First inauguration of Richard Nixon">the presidential inauguration</a>, and she appeared on a <a href="/wiki/Float_(parade)" title="Float (parade)">float</a> in the <a href="/wiki/United_States_presidential_inauguration#Inaugural_parade" title="United States presidential inauguration">inaugural parade</a> <i>(pictured)</i>. The phrase "Bring Us Together" was used ironically by <a href="/wiki/Democratic_Party_(United_States)" title="Democratic Party (United States)">Democrats</a> when Nixon proposed policies with which they disagreed. In newspaper columns written in the final years before his 2009 death, Safire expressed doubt that Cole\'s sign had ever existed. (<b><a href="/wiki/Bring_Us_Together" title="Bring Us Together">Full&#160;article...</a></b>)\n</p>\n<div class="tfa-recent" style="text-align: right;">\nRecently featured: <div class="hlist hlist-separated inline">\n<ul><li>"<a href="/wiki/Watching_the_River_Flow" title="Watching the River Flow">Watching the River Flow</a>"</li>\n<li><a href="/wiki/Warner_Bros._Movie_World" title="Warner Bros. Movie World">Warner Bros. Movie World</a></li>\n<li><a href="/wiki/Treaty_of_Lutatius" title="Treaty of Lutatius">Treaty of Lutatius</a></li></ul>\n</div></div>\n<div class="tfa-footer hlist hlist-separated noprint" style="text-align: right;">\n<ul><li><b><a href="/wiki/Wikipedia:Today%27s_featured_article/June_2021" title="Wikipedia:Today&#39;s featured article/June 2021">Archive</a></b></li>\n<li><b><a href="https://lists.wikimedia.org/mailman/listinfo/daily-article-l" class="extiw" title="mail:daily-article-l">By email</a></b></li>\n<li><b><a href="/wiki/Wikipedia:Featured_articles" title="Wikipedia:Featured articles">More featured articles</a></b></li></ul>\n</div></div>\n<h2 id="mp-dyk-h2" class="mp-h2"><span class="mw-headline" id="Did_you_know_...">Did you know&#160;...</span></h2>\n<div id="mp-dyk">\n<div class="dyk-img" style="float: right; margin-left: 0.5em;">\n<div class="thumbinner mp-thumb" style="background: transparent; border: none; padding: 0; max-width: 114px;">\n<a href="/wiki/File:Portrait_de_Dante.jpg" class="image" title="Portrait of Dante by Botticelli"><img alt="Portrait of Dante by Botticelli" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Portrait_de_Dante.jpg/114px-Portrait_de_Dante.jpg" decoding="async" width="114" height="173" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Portrait_de_Dante.jpg/171px-Portrait_de_Dante.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Portrait_de_Dante.jpg/228px-Portrait_de_Dante.jpg 2x" data-file-width="1000" data-file-height="1519" /></a><div class="thumbcaption" style="padding: 0.25em 0; word-wrap: break-word;">Portrait of Dante by <a href="/wiki/Sandro_Botticelli" title="Sandro Botticelli">Botticelli</a></div></div>\n</div>\n<ul><li>... that the bones of <a href="/wiki/Dante_Alighieri" title="Dante Alighieri">Dante</a> <i>(pictured)</i> were to be taken to <a href="/wiki/Benito_Mussolini" title="Benito Mussolini">Mussolini</a>\'s intended last stand against the <a href="/wiki/Allies_of_World_War_II" title="Allies of World War II">Allies</a> at the <b><a href="/wiki/Valtellina_Redoubt" title="Valtellina Redoubt">Valtellina Redoubt</a></b>?</li>\n<li>... that 110 <a href="/wiki/Taxon" title="Taxon">taxa</a> are classed as being <a href="/wiki/Extinction" title="Extinction">extinct</a> on the <b><a href="/wiki/Japanese_Red_List" title="Japanese Red List">Japanese Red List</a></b>, including the <a href="/wiki/Hokkaido_wolf" title="Hokkaido wolf">Hokkaido wolf</a>?</li>\n<li>... that the last five minutes of <b><a href="/wiki/Coventry_City_2%E2%80%932_Bristol_City_(1977)" title="Coventry City 2\xe2\x80\x932 Bristol City (1977)">a 1977 game</a></b> between <a href="/wiki/Coventry_City_F.C." title="Coventry City F.C.">Coventry City</a> and <a href="/wiki/Bristol_City_F.C." title="Bristol City F.C.">Bristol City</a> were played with neither team attempting to score?</li>\n<li>... that <b><a href="/wiki/Sindee_Simon" title="Sindee Simon">Sindee Simon</a></b> studied ancient <a href="/wiki/Amber" title="Amber">amber</a> to show that <a href="/wiki/Glass#Reputed_flow" title="Glass">glass does not flow</a>?</li>\n<li>... that concert pianist, composer, and opera librettist <b><a href="/wiki/Leonard_Liebling" title="Leonard Liebling">Leonard Liebling</a></b> was the editor-in-chief of the <i><a href="/wiki/Musical_Courier" title="Musical Courier">Musical Courier</a></i> from 1911 to 1945?</li>\n<li>... that the principal of <b><a href="/wiki/Frontier_Central_School_District" title="Frontier Central School District">Big Tree Elementary</a></b> read a book from a <a href="/wiki/Hot-air_balloon" title="Hot-air balloon">hot-air balloon</a> to honor her students for having collectively read more than 2.5&#160;million minutes in 2006?</li>\n<li>... that <b><a href="/wiki/Kartini_Hermanus" title="Kartini Hermanus">Kartini Hermanus</a></b>, the first female general in the <a href="/wiki/Indonesian_Army" title="Indonesian Army">Indonesian Army</a>, outranked her husband after being promoted in 2000?</li>\n<li>... that landslides caused by <a href="/wiki/Tropical_Storm_Talas_(2011)" title="Tropical Storm Talas (2011)">Tropical Storm Talas</a> delayed a realignment project on <b><a href="/wiki/Japan_National_Route_424" title="Japan National Route 424">Japan National Route&#160;424</a></b>?</li></ul>\n<div class="dyk-footer hlist noprint" style="margin-top: 0.5em; text-align: right;">\n<ul><li><b><a href="/wiki/Wikipedia:Recent_additions" title="Wikipedia:Recent additions">Archive</a></b></li>\n<li><b><a href="/wiki/Help:Your_first_article" title="Help:Your first article">Start a new articl

In [218]:
soup = BeautifulSoup(wiki_page.content)

In [219]:
pretty_soup = soup.prettify

Extracting 1 Header

In [220]:
headers = soup.find_all('span',class_='mw-headline')

In [221]:
headers

[<span class="mw-headline" id="From_today's_featured_article">From today's featured article</span>,
 <span class="mw-headline" id="Did_you_know_...">Did you know ...</span>,
 <span class="mw-headline" id="In_the_news">In the news</span>,
 <span class="mw-headline" id="On_this_day">On this day</span>,
 <span class="mw-headline" id="From_today's_featured_list">From today's featured list</span>,
 <span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span>,
 <span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span>,
 <span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span>,
 <span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span>]

In [222]:
headers_tag = []
for i in headers:
    headers_tag.append(i.text)

In [223]:
for i in headers_tag:
    print(i)

From today's featured article
Did you know ...
In the news
On this day
From today's featured list
Today's featured picture
Other areas of Wikipedia
Wikipedia's sister projects
Wikipedia languages

### 2. Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. Name, IMDB rating, Year of
### release) and make data frame.

In [224]:
imdb = requests.get('https://www.imdb.com/chart/top/')

In [225]:
imdb

In [226]:
soup1 = BeautifulSoup(imdb.content)

In [227]:
year = soup1.find_all('span',class_='secondaryInfo')

In [228]:
len(year)

250

In [229]:
movies = soup1.find_all('td',class_='titleColumn')

In [230]:
movies

[<td class="titleColumn">
       1.
       <a href="/title/tt0111161/" title="Frank Darabont (dir.), Tim Robbins, Morgan Freeman">The Shawshank Redemption</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       2.
       <a href="/title/tt0068646/" title="Francis Ford Coppola (dir.), Marlon Brando, Al Pacino">The Godfather</a>
 <span class="secondaryInfo">(1972)</span>
 </td>,
 <td class="titleColumn">
       3.
       <a href="/title/tt0071562/" title="Francis Ford Coppola (dir.), Al Pacino, Robert De Niro">The Godfather: Part II</a>
 <span class="secondaryInfo">(1974)</span>
 </td>,
 <td class="titleColumn">
       4.
       <a href="/title/tt0468569/" title="Christopher Nolan (dir.), Christian Bale, Heath Ledger">The Dark Knight</a>
 <span class="secondaryInfo">(2008)</span>
 </td>,
 <td class="titleColumn">
       5.
       <a href="/title/tt0050083/" title="Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb">12 Angry Men</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       6.
       <a href="/title/tt0108052/" title="Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes">Schindler's List</a>
 <span class="secondaryInfo">(1993)</span>
 </td>,
 <td class="titleColumn">
       7.
       <a href="/title/tt0167260/" title="Peter Jackson (dir.), Elijah Wood, Viggo Mortensen">The Lord of the Rings: The Return of the King</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       8.
       <a href="/title/tt0110912/" title="Quentin Tarantino (dir.), John Travolta, Uma Thurman">Pulp Fiction</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       9.
       <a href="/title/tt0060196/" title="Sergio Leone (dir.), Clint Eastwood, Eli Wallach">Il buono, il brutto, il cattivo</a>
 <span class="secondaryInfo">(1966)</span>
 </td>,
 <td class="titleColumn">
       10.
       <a href="/title/tt0120737/" title="Peter Jackson (dir.), Elijah Wood, Ian McKellen">The Lord of the Rings: The Fellowship of the Ring</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       11.
       <a href="/title/tt0137523/" title="David Fincher (dir.), Brad Pitt, Edward Norton">Fight Club</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       12.
       <a href="/title/tt0109830/" title="Robert Zemeckis (dir.), Tom Hanks, Robin Wright">Forrest Gump</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       13.
       <a href="/title/tt1375666/" title="Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt">Inception</a>
 <span class="secondaryInfo">(2010)</span>
 </td>,
 <td class="titleColumn">
       14.
       <a href="/title/tt0167261/" title="Peter Jackson (dir.), Elijah Wood, Ian McKellen">The Lord of the Rings: The Two Towers</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       15.
       <a href="/title/tt0080684/" title="Irvin Kershner (dir.), Mark Hamill, Harrison Ford">Star Wars: Episode V - The Empire Strikes Back</a>
 <span class="secondaryInfo">(1980)</span>
 </td>,
 <td class="titleColumn">
       16.
       <a href="/title/tt0133093/" title="Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne">The Matrix</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       17.
       <a href="/title/tt0099685/" title="Martin Scorsese (dir.), Robert De Niro, Ray Liotta">Goodfellas</a>
 <span class="secondaryInfo">(1990)</span>
 </td>,
 <td class="titleColumn">
       18.
       <a href="/title/tt0073486/" title="Milos Forman (dir.), Jack Nicholson, Louise Fletcher">One Flew Over the Cuckoo's Nest</a>
 <span class="secondaryInfo">(1975)</span>
 </td>,
 <td class="titleColumn">
       19.
       <a href="/title/tt0047478/" title="Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura">Shichinin no samurai</a>
 <span class="secondaryInfo">(1954)</span>
 </td>,
 <td class="titleColumn">
       20.
       <a href="/title/tt0114369/" title="David Fincher (dir.), Morgan Freeman, Brad Pitt">Se7en</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       21.
       <a href="/title/tt0102926/" title="Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins">The Silence of the Lambs</a>
 <span class="secondaryInfo">(1991)</span>
 </td>,
 <td class="titleColumn">
       22.
       <a href="/title/tt0317248/" title="Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino">Cidade de Deus</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       23.
       <a href="/title/tt0038650/" title="Frank Capra (dir.), James Stewart, Donna Reed">It's a Wonderful Life</a>
 <span class="secondaryInfo">(1946)</span>
 </td>,
 <td class="titleColumn">
       24.
       <a href="/title/tt0118799/" title="Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi">La vita è bella</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       25.
       <a href="/title/tt0076759/" title="George Lucas (dir.), Mark Hamill, Harrison Ford">Star Wars</a>
 <span class="secondaryInfo">(1977)</span>
 </td>,
 <td class="titleColumn">
       26.
       <a href="/title/tt0120815/" title="Steven Spielberg (dir.), Tom Hanks, Matt Damon">Saving Private Ryan</a>
 <span class="secondaryInfo">(1998)</span>
 </td>,
 <td class="titleColumn">
       27.
       <a href="/title/tt0245429/" title="Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette">Sen to Chihiro no kamikakushi</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       28.
       <a href="/title/tt0120689/" title="Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan">The Green Mile</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       29.
       <a href="/title/tt0816692/" title="Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway">Interstellar</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       30.
       <a href="/title/tt6751668/" title="Bong Joon Ho (dir.), Kang-ho Song, Sun-kyun Lee">Gisaengchung</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       31.
       <a href="/title/tt0110413/" title="Luc Besson (dir.), Jean Reno, Gary Oldman">Léon</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       32.
       <a href="/title/tt0056058/" title="Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama">Seppuku</a>
 <span class="secondaryInfo">(1962)</span>
 </td>,
 <td class="titleColumn">
       33.
       <a href="/title/tt0114814/" title="Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne">The Usual Suspects</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       34.
       <a href="/title/tt0253474/" title="Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann">The Pianist</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       35.
       <a href="/title/tt0088763/" title="Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd">Back to the Future</a>
 <span class="secondaryInfo">(1985)</span>
 </td>,
 <td class="titleColumn">
       36.
       <a href="/title/tt0103064/" title="James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton">Terminator 2: Judgment Day</a>
 <span class="secondaryInfo">(1991)</span>
 </td>,
 <td class="titleColumn">
       37.
       <a href="/title/tt0027977/" title="Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard">Modern Times</a>
 <span class="secondaryInfo">(1936)</span>
 </td>,
 <td class="titleColumn">
       38.
       <a href="/title/tt0054215/" title="Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh">Psycho</a>
 <span class="secondaryInfo">(1960)</span>
 </td>,
 <td class="titleColumn">
       39.
       <a href="/title/tt0110357/" title="Roger Allers (dir.), Matthew Broderick, Jeremy Irons">The Lion King</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       40.
       <a href="/title/tt0120586/" title="Tony Kaye (dir.), Edward Norton, Edward Furlong">American History X</a>
 <span class="secondaryInfo">(1998)</span>
 </td>,
 <td class="titleColumn">
       41.
       <a href="/title/tt0021749/" title="Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill">City Lights</a>
 <span class="secondaryInfo">(1931)</span>
 </td>,
 <td class="titleColumn">
       42.
       <a href="/title/tt0172495/" title="Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix">Gladiator</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       43.
       <a href="/title/tt2582802/" title="Damien Chazelle (dir.), Miles Teller, J.K. Simmons">Whiplash</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       44.
       <a href="/title/tt0407887/" title="Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon">The Departed</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       45.
       <a href="/title/tt0095327/" title="Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi">Hotaru no haka</a>
 <span class="secondaryInfo">(1988)</span>
 </td>,
 <td class="titleColumn">
       46.
       <a href="/title/tt1675434/" title="Olivier Nakache (dir.), François Cluzet, Omar Sy">The Intouchables</a>
 <span class="secondaryInfo">(2011)</span>
 </td>,
 <td class="titleColumn">
       47.
       <a href="/title/tt0482571/" title="Christopher Nolan (dir.), Christian Bale, Hugh Jackman">The Prestige</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       48.
       <a href="/title/tt0034583/" title="Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman">Casablanca</a>
 <span class="secondaryInfo">(1942)</span>
 </td>,
 <td class="titleColumn">
       49.
       <a href="/title/tt0064116/" title="Sergio Leone (dir.), Henry Fonda, Charles Bronson">Once Upon a Time in the West</a>
 <span class="secondaryInfo">(1968)</span>
 </td>,
 <td class="titleColumn">
       50.
       <a href="/title/tt0047396/" title="Alfred Hitchcock (dir.), James Stewart, Grace Kelly">Rear Window</a>
 <span class="secondaryInfo">(1954)</span>
 </td>,
 <td class="titleColumn">
       51.
       <a href="/title/tt0095765/" title="Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale">Nuovo Cinema Paradiso</a>
 <span class="secondaryInfo">(1988)</span>
 </td>,
 <td class="titleColumn">
       52.
       <a href="/title/tt0078748/" title="Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt">Alien</a>
 <span class="secondaryInfo">(1979)</span>
 </td>,
 <td class="titleColumn">
       53.
       <a href="/title/tt0078788/" title="Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando">Apocalypse Now</a>
 <span class="secondaryInfo">(1979)</span>
 </td>,
 <td class="titleColumn">
       54.
       <a href="/title/tt0209144/" title="Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss">Memento</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       55.
       <a href="/title/tt0082971/" title="Steven Spielberg (dir.), Harrison Ford, Karen Allen">Raiders of the Lost Ark</a>
 <span class="secondaryInfo">(1981)</span>
 </td>,
 <td class="titleColumn">
       56.
       <a href="/title/tt0032553/" title="Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard">The Great Dictator</a>
 <span class="secondaryInfo">(1940)</span>
 </td>,
 <td class="titleColumn">
       57.
       <a href="/title/tt0405094/" title="Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck">The Lives of Others</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       58.
       <a href="/title/tt1853728/" title="Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz">Django Unchained</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       59.
       <a href="/title/tt0050825/" title="Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker">Paths of Glory</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       60.
       <a href="/title/tt0043014/" title="Billy Wilder (dir.), William Holden, Gloria Swanson">Sunset Blvd.</a>
 <span class="secondaryInfo">(1950)</span>
 </td>,
 <td class="titleColumn">
       61.
       <a href="/title/tt0910970/" title="Andrew Stanton (dir.), Ben Burtt, Elissa Knight">WALL·E</a>
 <span class="secondaryInfo">(2008)</span>
 </td>,
 <td class="titleColumn">
       62.
       <a href="/title/tt0081505/" title="Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall">The Shining</a>
 <span class="secondaryInfo">(1980)</span>
 </td>,
 <td class="titleColumn">
       63.
       <a href="/title/tt0051201/" title="Billy Wilder (dir.), Tyrone Power, Marlene Dietrich">Witness for the Prosecution</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       64.
       <a href="/title/tt4154756/" title="Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth">Avengers: Infinity War</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       65.
       <a href="/title/tt7286456/" title="Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro">Joker</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       66.
       <a href="/title/tt0057012/" title="Stanley Kubrick (dir.), Peter Sellers, George C. Scott">Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb</a>
 <span class="secondaryInfo">(1964)</span>
 </td>,
 <td class="titleColumn">
       67.
       <a href="/title/tt4633694/" title="Bob Persichetti (dir.), Shameik Moore, Jake Johnson">Spider-Man: Into the Spider-Verse</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       68.
       <a href="/title/tt0364569/" title="Chan-wook Park (dir.), Choi Min-sik, Yoo Ji-Tae">Oldeuboi</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       69.
       <a href="/title/tt0119698/" title="Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida">Mononoke-hime</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       70.
       <a href="/title/tt8503618/" title="Thomas Kail (dir.), Lin-Manuel Miranda, Phillipa Soo">Hamilton</a>
 <span class="secondaryInfo">(2020)</span>
 </td>,
 <td class="titleColumn">
       71.
       <a href="/title/tt0087843/" title="Sergio Leone (dir.), Robert De Niro, James Woods">Once Upon a Time in America</a>
 <span class="secondaryInfo">(1984)</span>
 </td>,
 <td class="titleColumn">
       72.
       <a href="/title/tt5311514/" title="Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi">Kimi no na wa.</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       73.
       <a href="/title/tt1345836/" title="Christopher Nolan (dir.), Christian Bale, Tom Hardy">The Dark Knight Rises</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       74.
       <a href="/title/tt0090605/" title="James Cameron (dir.), Sigourney Weaver, Michael Biehn">Aliens</a>
 <span class="secondaryInfo">(1986)</span>
 </td>,
 <td class="titleColumn">
       75.
       <a href="/title/tt0048473/" title="Satyajit Ray (dir.), Kanu Bannerjee, Karuna Bannerjee">Pather Panchali</a>
 <span class="secondaryInfo">(1955)</span>
 </td>,
 <td class="titleColumn">
       76.
       <a href="/title/tt2380307/" title="Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal">Coco</a>
 <span class="secondaryInfo">(2017)</span>
 </td>,
 <td class="titleColumn">
       77.
       <a href="/title/tt0082096/" title="Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer">Das Boot</a>
 <span class="secondaryInfo">(1981)</span>
 </td>,
 <td class="titleColumn">
       78.
       <a href="/title/tt8267604/" title="Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw">Capharnaüm</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       79.
       <a href="/title/tt0057565/" title="Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada">Tengoku to jigoku</a>
 <span class="secondaryInfo">(1963)</span>
 </td>,
 <td class="titleColumn">
       80.
       <a href="/title/tt4154796/" title="Anthony Russo (dir.), Robert Downey Jr., Chris Evans">Avengers: Endgame</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       81.
       <a href="/title/tt0169547/" title="Sam Mendes (dir.), Kevin Spacey, Annette Bening">American Beauty</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       82.
       <a href="/title/tt0114709/" title="John Lasseter (dir.), Tom Hanks, Tim Allen">Toy Story</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       83.
       <a href="/title/tt0112573/" title="Mel Gibson (dir.), Mel Gibson, Sophie Marceau">Braveheart</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       84.
       <a href="/title/tt0086879/" title="Milos Forman (dir.), F. Murray Abraham, Tom Hulce">Amadeus</a>
 <span class="secondaryInfo">(1984)</span>
 </td>,
 <td class="titleColumn">
       85.
       <a href="/title/tt1187043/" title="Rajkumar Hirani (dir.), Aamir Khan, Madhavan">3 Idiots</a>
 <span class="secondaryInfo">(2009)</span>
 </td>,
 <td class="titleColumn">
       86.
       <a href="/title/tt0361748/" title="Quentin Tarantino (dir.), Brad Pitt, Diane Kruger">Inglourious Basterds</a>
 <span class="secondaryInfo">(2009)</span>
 </td>,
 <td class="titleColumn">
       87.
       <a href="/title/tt0119217/" title="Gus Van Sant (dir.), Robin Williams, Matt Damon">Good Will Hunting</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       88.
       <a href="/title/tt0086190/" title="Richard Marquand (dir.), Mark Hamill, Harrison Ford">Star Wars: Episode VI - Return of the Jedi</a>
 <span class="secondaryInfo">(1983)</span>
 </td>,
 <td class="titleColumn">
       89.
       <a href="/title/tt0062622/" title="Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood">2001: A Space Odyssey</a>
 <span class="secondaryInfo">(1968)</span>
 </td>,
 <td class="titleColumn">
       90.
       <a href="/title/tt0105236/" title="Quentin Tarantino (dir.), Harvey Keitel, Tim Roth">Reservoir Dogs</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       91.
       <a href="/title/tt0022100/" title="Fritz Lang (dir.), Peter Lorre, Ellen Widmann">M - Eine Stadt sucht einen Mörder</a>
 <span class="secondaryInfo">(1931)</span>
 </td>,
 <td class="titleColumn">
       92.
       <a href="/title/tt0986264/" title="Aamir Khan (dir.), Darsheel Safary, Aamir Khan">Taare Zameen Par</a>
 <span class="secondaryInfo">(2007)</span>
 </td>,
 <td class="titleColumn">
       93.
       <a href="/title/tt0033467/" title="Orson Welles (dir.), Orson Welles, Joseph Cotten">Citizen Kane</a>
 <span class="secondaryInfo">(1941)</span>
 </td>,
 <td class="titleColumn">
       94.
       <a href="/title/tt0052357/" title="Alfred Hitchcock (dir.), James Stewart, Kim Novak">Vertigo</a>
 <span class="secondaryInfo">(1958)</span>
 </td>,
 <td class="titleColumn">
       95.
       <a href="/title/tt0180093/" title="Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto">Requiem for a Dream</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       96.
       <a href="/title/tt2106476/" title="Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen">Jagten</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       97.
       <a href="/title/tt0045152/" title="Stanley Donen (dir.), Gene Kelly, Donald O'Connor">Singin' in the Rain</a>
 <span class="secondaryInfo">(1952)</span>
 </td>,
 <td class="titleColumn">
       98.

In [231]:
movies_all = []
years= []
for i in movies[:100]:
    for j in i.find('a'):
        movies_all.append(j)

In [232]:
for i in movies[:100]:
    for j in i.find('span'):
        years.append(j)

In [233]:
len(movies_all)

100

In [234]:
release_year = []
for i in years[:100]:
    release_year.append(i[1:-1])

In [235]:
rating = soup1.find_all('td',class_='ratingColumn imdbRating')

In [236]:
ratings = []

In [237]:

for i in rating[:100]:
    for j in i.find('strong'):
        ratings.append(j)

In [238]:
len(ratings)

100

In [239]:
import pandas as pd

In [240]:
imbd_top_dict = {
    'Movie': movies_all,
    'Release Year': release_year,
    'Rating': ratings
}

In [241]:
imbd_top_100 = pd.DataFrame(imbd_top_dict)

In [242]:
imbd_top_100.dtypes

Movie           object
Release Year    object
Rating          object
dtype: object

In [243]:
imbd_top_100.Rating = imbd_top_100.Rating.astype('float')

In [244]:
imbd_top_100['Release Year'] =imbd_top_100['Release Year'].astype('int')

In [245]:
imbd_top_100.dtypes

Movie            object
Release Year      int32
Rating          float64
dtype: object

In [246]:
imbd_top_100

                                    Movie  Release Year  Rating
0                The Shawshank Redemption          1994     9.2
1                           The Godfather          1972     9.1
2                  The Godfather: Part II          1974     9.0
3                         The Dark Knight          2008     9.0
4                            12 Angry Men          1957     8.9
..                                    ...           ...     ...
95                                 Jagten          2012     8.3
96                    Singin' in the Rain          1952     8.3
97                     North by Northwest          1959     8.3
98                           Idi i smotri          1985     8.3
99  Eternal Sunshine of the Spotless Mind          2004     8.3

[100 rows x 3 columns]

In [247]:
imbd_top_100.dtypes

Movie            object
Release Year      int32
Rating          float64
dtype: object

In [248]:
imbd_top_100.describe()

       Release Year      Rating
count    100.000000  100.000000
mean    1987.480000    8.478000
std       22.974945    0.199788
min     1931.000000    8.300000
25%     1973.500000    8.300000
50%     1994.000000    8.400000
75%     2003.250000    8.525000
max     2020.000000    9.200000

### 3. Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. Name, IMDB rating, Year of release) and make data frame

In [249]:
imdb_hindi_request = requests.get('https://www.imdb.com/india/top-rated-indian-movies')

In [250]:
imdb_hindi_request

In [251]:
soup2 = BeautifulSoup(imdb_hindi_request.content)

In [252]:
movies_name = soup2.find_all('td',class_='titleColumn')

In [253]:
movies_name

[<td class="titleColumn">
       1.
       <a href="/title/tt0048473/" title="Satyajit Ray (dir.), Kanu Bannerjee, Karuna Bannerjee">Pather Panchali</a>
 <span class="secondaryInfo">(1955)</span>
 </td>,
 <td class="titleColumn">
       2.
       <a href="/title/tt0093603/" title="Mani Ratnam (dir.), Kamal Haasan, Saranya Ponvannan">Nayakan</a>
 <span class="secondaryInfo">(1987)</span>
 </td>,
 <td class="titleColumn">
       3.
       <a href="/title/tt8176054/" title="Mari Selvaraj (dir.), Kathir, Anandhi">Pariyerum Perumal</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       4.
       <a href="/title/tt0367495/" title="Sundar C. (dir.), Kamal Haasan, Madhavan">Anbe Sivam</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       5.
       <a href="/title/tt0079221/" title="Hrishikesh Mukherjee (dir.), Amol Palekar, Bindiya Goswami">Golmaal</a>
 <span class="secondaryInfo">(1979)</span>
 </td>,
 <td class="titleColumn">
       6.
       <a href="/title/tt0052572/" title="Satyajit Ray (dir.), Soumitra Chatterjee, Sharmila Tagore">Apur Sansar</a>
 <span class="secondaryInfo">(1959)</span>
 </td>,
 <td class="titleColumn">
       7.
       <a href="/title/tt7391996/" title="Venkatesh Maha (dir.), Radha Bessy, Subba Rao Vepada">C/o Kancharapalem</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       8.
       <a href="/title/tt0237376/" title="Sibi Malayil (dir.), Mohanlal, Thilakan">Kireedam</a>
 <span class="secondaryInfo">(1989)</span>
 </td>,
 <td class="titleColumn">
       9.
       <a href="/title/tt0214915/" title="Fazil (dir.), Mohanlal, Shobana">Manichitrathazhu</a>
 <span class="secondaryInfo">(1993)</span>
 </td>,
 <td class="titleColumn">
       10.
       <a href="/title/tt5311546/" title="Mahesh Manjrekar (dir.), Nana Patekar, Medha Manjrekar">Natsamrat</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       11.
       <a href="/title/tt12361178/" title="Jeethu Joseph (dir.), Mohanlal, Meena">Drishyam 2</a>
 <span class="secondaryInfo">(2021)</span>
 </td>,
 <td class="titleColumn">
       12.
       <a href="/title/tt7019842/" title="C. Prem Kumar (dir.), Vijay Sethupathi, Adithya Bhaskar">96</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       13.
       <a href="/title/tt0400234/" title="Anurag Kashyap (dir.), Kay Kay Menon, Pawan Malhotra">Black Friday</a>
 <span class="secondaryInfo">(2004)</span>
 </td>,
 <td class="titleColumn">
       14.
       <a href="/title/tt0105575/" title="Bharathan (dir.), Kamal Haasan, Shivaji Ganesan">Thevar Magan</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       15.
       <a href="/title/tt8413338/" title="Madhu C. Narayanan (dir.), Shane Nigam, Soubin Shahir">Kumbalangi Nights</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       16.
       <a href="/title/tt1187043/" title="Rajkumar Hirani (dir.), Aamir Khan, Madhavan">3 Idiots</a>
 <span class="secondaryInfo">(2009)</span>
 </td>,
 <td class="titleColumn">
       17.
       <a href="/title/tt4991384/" title="Vetrimaaran (dir.), Dinesh, Samuthirakani">Visaaranai</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       18.
       <a href="/title/tt0986264/" title="Aamir Khan (dir.), Darsheel Safary, Aamir Khan">Taare Zameen Par</a>
 <span class="secondaryInfo">(2007)</span>
 </td>,
 <td class="titleColumn">
       19.
       <a href="/title/tt8948790/" title="Gowtam Tinnanuri (dir.), Nani, Shraddha Srinath">Jersey</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       20.
       <a href="/title/tt7060344/" title="Ram Kumar (dir.), Vishnu Vishal, Amala Paul">Ratsasan</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       21.
       <a href="/title/tt0101649/" title="Mani Ratnam (dir.), Rajinikanth, Mammootty">Thalapathi</a>
 <span class="secondaryInfo">(1991)</span>
 </td>,
 <td class="titleColumn">
       22.
       <a href="/title/tt5074352/" title="Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar">Dangal</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       23.
       <a href="/title/tt10189514/" title="Sudha Kongara (dir.), Suriya, Madhavan">Soorarai Pottru</a>
 <span class="secondaryInfo">(2020)</span>
 </td>,
 <td class="titleColumn">
       24.
       <a href="/title/tt9477520/" title="Vetrimaaran (dir.), Dhanush, Manju Warrier">Asuran</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       25.
       <a href="/title/tt9900782/" title="Lokesh Kanagaraj (dir.), Karthi, Narain">Kaithi</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       26.
       <a href="/title/tt0048956/" title="Satyajit Ray (dir.), Pinaki Sengupta, Smaran Ghosal">Aparajito</a>
 <span class="secondaryInfo">(1956)</span>
 </td>,
 <td class="titleColumn">
       27.
       <a href="/title/tt0291855/" title="I.V. Sasi (dir.), Mohanlal, Revathi">Devasuram</a>
 <span class="secondaryInfo">(1993)</span>
 </td>,
 <td class="titleColumn">
       28.
       <a href="/title/tt0085743/" title="Kundan Shah (dir.), Naseeruddin Shah, Ravi Baswani">Jaane Bhi Do Yaaro</a>
 <span class="secondaryInfo">(1983)</span>
 </td>,
 <td class="titleColumn">
       29.
       <a href="/title/tt0050870/" title="Guru Dutt (dir.), Guru Dutt, Waheeda Rehman">Pyaasa</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       30.
       <a href="/title/tt0059246/" title="Vijay Anand (dir.), Dev Anand, Waheeda Rehman">Guide</a>
 <span class="secondaryInfo">(1965)</span>
 </td>,
 <td class="titleColumn">
       31.
       <a href="/title/tt7738784/" title="Ram (dir.), Mammootty, Sadhana">Peranbu</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       32.
       <a href="/title/tt5959980/" title="Vetrimaaran (dir.), Dhanush, Ameer Sultan">Vada Chennai</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       33.
       <a href="/title/tt4987556/" title="Mohan Raja (dir.), Jayam Ravi, Arvind Swamy">Thani Oruvan</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       34.
       <a href="/title/tt0312859/" title="Mani Ratnam (dir.), Madhavan, Simran">Kannathil Muthamittal</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       35.
       <a href="/title/tt0072783/" title="Hrishikesh Mukherjee (dir.), Dharmendra, Sharmila Tagore">Chupke Chupke</a>
 <span class="secondaryInfo">(1975)</span>
 </td>,
 <td class="titleColumn">
       36.
       <a href="/title/tt0119385/" title="Mani Ratnam (dir.), Mohanlal, Prakash Raj">Iruvar</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       37.
       <a href="/title/tt0292246/" title="Bhadran (dir.), Mohanlal, Thilakan">Spadikam</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       38.
       <a href="/title/tt10214826/" title="Swaroop Rsj (dir.), Naveen Polishetty, Shruti Sharma">Agent Sai Srinivasa Athreya</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       39.
       <a href="/title/tt3417422/" title="Jeethu Joseph (dir.), Mohanlal, Meena">Drishyam</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       40.
       <a href="/title/tt6148156/" title="Gayatri (dir.), Madhavan, Vijay Sethupathi">Vikram Vedha</a>
 <span class="secondaryInfo">(2017)</span>
 </td>,
 <td class="titleColumn">
       41.
       <a href="/title/tt7019942/" title="Thiagarajan Kumararaja (dir.), Vijay Sethupathi, Samantha Akkineni">Super Deluxe</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       42.
       <a href="/title/tt5867800/" title="Arun Prabhu Purushothaman (dir.), Aditi Balan, Padmashri Mohammad Ali">Aruvi</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       43.
       <a href="/title/tt8239946/" title="Rahi Anil Barve (dir.), Sohum Shah, Jyoti Malshe">Tumbbad</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       44.
       <a href="/title/tt7465992/" title="Nag Ashwin (dir.), Keerthy Suresh, Dulquer Salmaan">Mahanati</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       45.
       <a href="/title/tt0466460/" title="Dibakar Banerjee (dir.), Anupam Kher, Boman Irani">Khosla Ka Ghosla!</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       46.
       <a href="/title/tt0066763/" title="Hrishikesh Mukherjee (dir.), Rajesh Khanna, Amitabh Bachchan">Anand</a>
 <span class="secondaryInfo">(1971)</span>
 </td>,
 <td class="titleColumn">
       47.
       <a href="/title/tt0459516/" title="K. Selvaraghavan (dir.), Dhanush, Sneha">Pudhu Pettai</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       48.
       <a href="/title/tt4679210/" title="Alphonse Puthren (dir.), Nivin Pauly, Sai Pallavi">Premam</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       49.
       <a href="/title/tt3973410/" title="M. Manikandan (dir.), Ramesh, J. Vignesh">Kaakkaa Muttai</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       50.
       <a href="/title/tt0376127/" title="S. Shankar (dir.), Vikram, Sada">Anniyan</a>
 <span class="secondaryInfo">(2005)</span>
 </td>,
 <td class="titleColumn">
       51.
       <a href="/title/tt8108198/" title="Sriram Raghavan (dir.), Ayushmann Khurrana, Tabu">Andhadhun</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       52.
       <a href="/title/tt3668162/" title="Anjali Menon (dir.), Nazriya Nazim, Nivin Pauly">Bangalore Days</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       53.
       <a href="/title/tt6380520/" title="Karthick Naren (dir.), Rahman, Prakash Raghavan">Dhuruvangal Pathinaaru</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       54.
       <a href="/title/tt0220656/" title="S. Shankar (dir.), Arjun Sarja, Manisha Koirala">Mudhalvan</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       55.
       <a href="/title/tt0195231/" title="Ram Gopal Varma (dir.), J.D. Chakravarthi, Manoj Bajpayee">Satya</a>
 <span class="secondaryInfo">(1998)</span>
 </td>,
 <td class="titleColumn">
       56.
       <a href="/title/tt4429128/" title="Jeethu Joseph (dir.), Kamal Haasan, Gautami">Papanasam</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       57.
       <a href="/title/tt2181831/" title="Hansal Mehta (dir.), Rajkummar Rao, Prabhleen Sandhu">Shahid</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       58.
       <a href="/title/tt2877108/" title="Nalan Kumarasamy (dir.), Vijay Sethupathi, Sanchita Shetty">Soodhu Kavvum</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       59.
       <a href="/title/tt3569782/" title="Karthik Subbaraj (dir.), Siddharth, Bobby Simha">Jigarthanda</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       60.
       <a href="/title/tt0376076/" title="Bala (dir.), Vikram, Suriya">Pithamagan</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       61.
       <a href="/title/tt1954470/" title="Anurag Kashyap (dir.), Manoj Bajpayee, Richa Chadha">Gangs of Wasseypur</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       62.
       <a href="/title/tt1620933/" title="Tigmanshu Dhulia (dir.), Irrfan Khan, Mahie Gill">Paan Singh Tomar</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       63.
       <a href="/title/tt5312232/" title="Nagraj Manjule (dir.), Rinku Rajguru, Akash Thosar">Sairat</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       64.
       <a href="/title/tt2356180/" title="Rakeysh Omprakash Mehra (dir.), Farhan Akhtar, Sonam Kapoor">Bhaag Milkha Bhaag</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       65.
       <a href="/title/tt4934950/" title="Meghna Gulzar (dir.), Irrfan Khan, Konkona Sen Sharma">Talvar</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       66.
       <a href="/title/tt0242519/" title="Priyadarshan (dir.), Akshay Kumar, Sunil Shetty">Hera Pheri</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       67.
       <a href="/title/tt0367110/" title="Ashutosh Gowariker (dir.), Shah Rukh Khan, Gayatri Joshi">Swades: We, the People</a>
 <span class="secondaryInfo">(2004)</span>
 </td>,
 <td class="titleColumn">
       68.
       <a href="/title/tt0073707/" title="Ramesh Sippy (dir.), Sanjeev Kumar, Dharmendra">Sholay</a>
 <span class="secondaryInfo">(1975)</span>
 </td>,
 <td class="titleColumn">
       69.
       <a href="/title/tt0375611/" title="Sanjay Leela Bhansali (dir.), Amitabh Bachchan, Rani Mukerji">Black</a>
 <span class="secondaryInfo">(2005)</span>
 </td>,
 <td class="titleColumn">
       70.
       <a href="/title/tt0871510/" title="Shimit Amin (dir.), Shah Rukh Khan, Vidya Malvade">Chak De! India</a>
 <span class="secondaryInfo">(2007)</span>
 </td>,
 <td class="titleColumn">
       71.
       <a href="/title/tt2218988/" title="Anwar Rasheed (dir.), Dulquer Salmaan, Thilakan">Ustad Hotel</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       72.
       <a href="/title/tt5005684/" title="Ashwiny Iyer Tiwari (dir.), Swara Bhaskar, Ratna Pathak Shah">Nil Battey Sannata</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       73.
       <a href="/title/tt0104561/" title="Mansoor Khan (dir.), Aamir Khan, Ayesha Jhulka">Jo Jeeta Wohi Sikandar</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       74.
       <a href="/title/tt4430212/" title="Nishikant Kamat (dir.), Ajay Devgn, Shriya Saran">Drishyam</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       75.
       <a href="/title/tt0054098/" title="K. Asif (dir.), Prithviraj Kapoor, Madhubala">Mughal-E-Azam</a>
 <span class="secondaryInfo">(1960)</span>
 </td>,
 <td class="titleColumn">
       76.
       <a href="/title/tt0057935/" title="Satyajit Ray (dir.), Soumitra Chatterjee, Madhabi Mukherjee">Charulata</a>
 <span class="secondaryInfo">(1964)</span>
 </td>,
 <td class="titleColumn">
       77.
       <a href="/title/tt4851630/" title="Dileesh Pothan (dir.), Fahadh Faasil, Aparna Balamurali">Maheshinte Prathikaaram</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       78.
       <a href="/title/tt1562872/" title="Zoya Akhtar (dir.), Hrithik Roshan, Farhan Akhtar">Zindagi Na Milegi Dobara</a>
 <span class="secondaryInfo">(2011)</span>
 </td>,
 <td class="titleColumn">
       79.
       <a href="/title/tt10324144/" title="Anubhav Sinha (dir.), Ayushmann Khurrana, Nassar">Article 15</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       80.
       <a href="/title/tt1639426/" title="Vikramaditya Motwane (dir.), Rajat Barmecha, Ronit Roy">Udaan</a>
 <span class="secondaryInfo">(2010)</span>
 </td>,
 <td class="titleColumn">
       81.
       <a href="/title/tt1280558/" title="Neeraj Pandey (dir.), Anupam Kher, Naseeruddin Shah">A Wednesday</a>
 <span class="secondaryInfo">(2008)</span>
 </td>,
 <td class="titleColumn">
       82.
       <a href="/title/tt7060460/" title="H. Vinoth (dir.), Karthi, Rakul Preet Singh">Theeran adhigaaram ondru</a>
 <span class="secondaryInfo">(2017)</span>
 </td>,
 <td class="titleColumn">
       83.
       <a href="/title/tt3322420/" title="Vikas Bahl (dir.), Kangana Ranaut, Rajkummar Rao">Queen</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       84.
       <a href="/title/tt4635372/" title="Neeraj Ghaywan (dir.), Richa Chadha, Sanjay Mishra">Masaan</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       85.
       <a href="/title/tt0200087/" title="John Mathew Matthan (dir.), Aamir Khan, Naseeruddin Shah">Sarfarosh</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       86.
       <a href="/title/tt0374887/" title="Rajkumar Hirani (dir.), Sanjay Dutt, Arshad Warsi">Munna Bhai M.B.B.S.</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       87.
       <a href="/title/tt0242256/" title="Mani Ratnam (dir.), Madhavan, Shalini">Alai Payuthey</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       88.
       <a href="/title/tt0292490/" title="Farhan Akhtar (dir.), Aamir Khan, Saif Ali Khan">Dil Chahta Hai</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       89.
       <a href="/title/tt0105271/" title="Mani Ratnam (dir.), Arvind Swamy, Madhoo">Roja</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       90.
       <a href="/title/tt2283748/" title="Umesh Shukla (dir.), Paresh Rawal, Akshay Kumar">OMG: Oh My God!</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       91.
       <a href="/title/tt0139876/" title="Suresh Krishna (dir.), Rajinikanth, Nagma">Baasha</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       92.
       <a href="/title/tt0405508/" title="Rakeysh Omprakash Mehra (dir.), Aamir Khan, Soha Ali Khan">Rang De Basanti</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       93.
       <a href="/title/tt0169102/" title="Ashutosh Gowariker (dir.), Aamir Khan, Raghuvir Yadav">Lagaan: Once Upon a Time in India</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       94.
       <a href="/title/tt1821480/" title="Sujoy Ghosh (dir.), Vidya Balan, Parambrata Chattopadhyay">Kahaani</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       95.
       <a href="/title/tt0109117/" title="Rajkumar Santoshi (dir.), Aamir Khan, Salman Khan">Andaz Apna Apna</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       96.
       <a href="/title/tt9052870/" title="Nitesh Tiwari (dir.), Sushant Singh Rajput, Shraddha Kapoor">Chhichhore</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       97.
       <a href="/title/tt8291224/" title="Aditya Dhar (dir.), Vicky Kaushal, Paresh Rawal">Uri: The Surgical Strike</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       98.
       <a href="/title/tt0364647/" title="Kamal Haasan (dir.), Kamal Haasan, Abhirami">Virumandi</a>
 <span class="secondaryInfo">(2004)</span>
 </td>,
 <td class="titleColumn">
       99.
       <a href="/title/tt2338151/" title="Rajkumar Hirani (dir.), Aamir Khan, Anushka Sharma">PK</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       100.
       <a href="/title/tt2358592/" title="Pawan Kumar (dir.), Sathish Neenasam, Sruthi Hariharan">Lucia</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       101.
       <a href="/title/tt0453729/" title="Nagesh Kukunoor (dir.), Shreyas Talpade, Naseeruddin Shah">Iqbal</a>
 <span class="secondaryInfo">(2005)</span>
 </td>,
 <td class="titleColumn">
       102.
       <a href="/title/tt0843326/" title="Bhaskar (dir.), Siddharth, Genelia D'Souza">Bommarillu</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,

In [254]:
movies_hindi = []
for i in movies_name[:100]:
    for j in i.find('a'):
        movies_hindi.append(j)

In [255]:
release_year_hin = []
for i in movies_name[:100]:
    for j in i.find('span'):
        release_year_hin.append(j[1:-1])

In [256]:
ratings_hindi = soup2.find_all('td',class_='ratingColumn imdbRating')

In [257]:
ratings_hindi

[<td class="ratingColumn imdbRating">
 <strong title="8.5 based on 25,314 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 17,355 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 10,819 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 17,987 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 18,331 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 12,726 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 5,331 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 6,632 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 9,320 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 5,756 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 25,943 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 21,981 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 19,418 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 5,971 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 10,648 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 356,538 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 8,665 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 175,194 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 10,281 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 30,400 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 10,746 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 164,254 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 81,177 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 16,528 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 15,290 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 12,316 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 5,062 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 13,435 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 5,791 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 7,612 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 13,659 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 12,910 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 17,642 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 7,777 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 11,893 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 5,311 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 5,084 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 9,797 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 35,903 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 31,052 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 11,148 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 11,654 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 32,137 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 10,412 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 22,670 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 31,841 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 5,345 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 18,195 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 6,111 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 15,503 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 77,233 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 17,500 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 13,496 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 6,892 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 13,840 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 6,421 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 15,610 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 9,438 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 10,711 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,842 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 85,779 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 34,051 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,788 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 62,452 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 32,168 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 59,265 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 85,092 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 52,369 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 33,752 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 75,597 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 12,459 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 6,026 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 22,094 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 74,048 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 7,517 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,489 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 7,422 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 70,060 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 25,435 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 43,114 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 74,991 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,464 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 61,735 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 24,774 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 24,384 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 75,595 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,672 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 67,989 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 12,091 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 53,222 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 9,319 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 114,265 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 106,958 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 58,915 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 50,505 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 37,919 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 45,556 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,139 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 167,606 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,694 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 16,152 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 8,852 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 15,200 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 77,208 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 40,753 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 9,976 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 11,725 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 12,898 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 19,582 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 11,265 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 43,984 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,636 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 10,333 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 6,320 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 78,135 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,132 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,104 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 6,413 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,226 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 14,209 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 64,938 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 12,452 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 51,260 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,250 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 19,879 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 20,656 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,109 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 6,061 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 8,760 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 52,186 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 5,292 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 41,038 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 33,693 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,892 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 11,093 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 29,211 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 29,339 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 7,023 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 77,800 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 7,284 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 5,394 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 12,953 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 13,858 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 10,622 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 14,756 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 22,117 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 5,070 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,818 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 18,165 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 7,196 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 100,760 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 116,769 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,405 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 64,791 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 48,843 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 8,684 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,247 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 6,139 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,116 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 14,328 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,371 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,457 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 22,733 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 22,475 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,776 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 21,338 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 105,741 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 6,920 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 11,833 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 53,822 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 53,778 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 9,444 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 24,509 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 8,788 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 34,213 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,072 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 10,240 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 16,120 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 51,950 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 11,771 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 8,359 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,905 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 23,728 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 21,787 user ratings">7.8</strong>

In [258]:
ratings_100_hindi = []
for i in ratings_hindi[:100]:
    for j in i.find('strong'):
        ratings_100_hindi.append(j)

In [259]:
imbd_top_dict_hindi = {
    'Movie': movies_hindi,
    'Release Year': release_year_hin,
    'Rating': ratings_100_hindi
}

In [260]:
hindi_movies = pd.DataFrame(imbd_top_dict_hindi)

In [261]:
hindi_movies

                       Movie Release Year Rating
0            Pather Panchali         1955    8.5
1                    Nayakan         1987    8.5
2          Pariyerum Perumal         2018    8.5
3                 Anbe Sivam         2003    8.5
4                    Golmaal         1979    8.5
..                       ...          ...    ...
95                Chhichhore         2019    8.1
96  Uri: The Surgical Strike         2018    8.1
97                 Virumandi         2004    8.1
98                        PK         2014    8.1
99                     Lucia         2013    8.1

[100 rows x 3 columns]

In [262]:
hindi_movies.dtypes

Movie           object
Release Year    object
Rating          object
dtype: object

In [263]:
hindi_movies['Release Year'] = hindi_movies['Release Year'].astype('int32')

In [264]:
hindi_movies['Rating'] = hindi_movies['Rating'].astype('float')

In [265]:
hindi_movies.dtypes

Movie            object
Release Year      int32
Rating          float64
dtype: object

In [266]:
hindi_movies.describe()

       Release Year      Rating
count    100.000000  100.000000
mean    2004.260000    8.212000
std       16.654311    0.124137
min     1955.000000    8.100000
25%     1998.750000    8.100000
50%     2012.000000    8.200000
75%     2016.000000    8.300000
max     2021.000000    8.500000

## 4. Write a python program to scrap book name, author name, genre and book review of any 5 books from
‘www.bookpage.com’

        - AS the Front Page does not contain much Reviews, i am scrapping information from - https://bookpage.com/reviews

In [267]:
request_book = requests.get('https://bookpage.com/reviews')

In [268]:
request_book

In [269]:
soup_book = BeautifulSoup(request_book.content)

In [270]:
booknames = soup_book.find_all('h4',class_='italic')

In [271]:
booknames

[<h4 class="italic">
 <a href="/reviews/26324-mary-mccoy-indestructible-object-ya"> <span style="font-style:normal;">★ </span>Indestructible Object</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26304-clint-smith-how-word-passed-nonfiction"> <span style="font-style:normal;">★ </span>How the Word Is Passed</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26320-tia-williams-seven-days-june-romance"> <span style="font-style:normal;">★ </span>Seven Days in June</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26292-zakiya-dalila-harris-other-black-girl-fiction"> <span style="font-style:normal;">★ </span>The Other Black Girl</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26294-nana-nkweti-walking-cowrie-shells-fiction"> <span style="font-style:normal;">★ </span>Walking on Cowrie Shells</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26284-taylor-jenkins-reid-malibu-rising-fiction">Malibu Rising</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26356-jules-machias-both-can-be-true-childrens">Both Can Be True</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26291-marianne-cronin-one-hundred-years-lenni-margot-fiction"> <span style="font-style:normal;">★ </span>The One Hundred Years of Lenni and Margot</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26328-rachel-lynn-solomon-we-cant-keep-meeting-like-this-ya">We Can’t Keep Meeting Like This</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26313-elizabeth-letts-ride-her-life-biography"> <span style="font-style:normal;">★ </span>The Ride of Her Life</a>
 </h4>]

In [272]:
authornames = soup_book.find_all('p',class_='sans bold')

In [273]:
authornames

[<p class="sans bold">
 Mary McCoy
 </p>,
 <p class="sans bold">
 Clint Smith
 </p>,
 <p class="sans bold">
 Tia Williams
 </p>,
 <p class="sans bold">
 Zakiya Dalila Harris
 </p>,
 <p class="sans bold">
 Nana Nkweti
 </p>,
 <p class="sans bold">
 Taylor Jenkins Reid
 </p>,
 <p class="sans bold">
 Jules Machias
 </p>,
 <p class="sans bold">
 Marianne Cronin
 </p>,
 <p class="sans bold">
 Rachel Lynn Solomon
 </p>,
 <p class="sans bold">
 Elizabeth Letts
 </p>]

In [274]:
genres = soup_book.find_all('p',class_='genre-links hidden-phone')

In [275]:
genres

[<p class="genre-links hidden-phone">
 <a href="/search?book_genre=ya">YA</a>
  /
 <a href="/search?book_genre=ya_fiction">YA Fiction</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=nonfiction">Nonfiction</a>
  /
 <a href="/search?book_genre=american_history">American History</a>
  /
 <a href="/search?book_genre=african_american_history">African American History</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=romance">Romance</a>
  /
 <a href="/search?book_genre=contemporary_romance">Contemporary Romance</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=literary_fiction">Literary Fiction</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=short_stories">Short Stories</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=popular_fiction">Popular Fiction</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=children_s">Children's</a>
  /
 <a href="/search?book_genre=middle_grade">Middle Grade</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=popular_fiction">Popular Fiction</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=ya">YA</a>
  /
 <a href="/search?book_genre=ya_fiction">YA Fiction</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=nonfiction">Nonfiction</a>
  /
 <a href="/search?book_genre=biography">Biography</a>
  /
 <a href="/search?book_genre=animals">Animals</a>
 </p>]

In [276]:
book_names = []

for i in range(0,5):
    count = 0
    if(len(booknames[i].find('a'))==1):
        book_names.append(booknames[i].find('a').text)
    else:
        for j in booknames[i].find('a'):
            
            count = count+1
            if(count == 3):
                book_names.append(j)

In [277]:
book_names

['Indestructible Object',
 'How the Word Is Passed',
 'Seven Days in June',
 'The Other Black Girl',
 'Walking on Cowrie Shells']

In [278]:
authors = []
for i in authornames[:5]:
    authors.append(i.text.replace('\n',''))

In [279]:
authors

['Mary McCoy',
 'Clint Smith',
 'Tia Williams',
 'Zakiya Dalila Harris',
 'Nana Nkweti']

In [280]:
genres_names = []
for i in genres[:5]:
   # for j in i.find('a'):
    genres_names.append(i.text.replace('\n',''))

In [281]:
genres_names

['YA / YA Fiction',
 'Nonfiction / American History / African American History',
 'Romance / Contemporary Romance',
 'Fiction / Literary Fiction',
 'Fiction / Short Stories']

In [282]:
reviews = soup_book.find_all('div',class_='flex-article-content')

In [283]:
reviews

[<div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26324-mary-mccoy-indestructible-object-ya"> <span style="font-style:normal;">★ </span>Indestructible Object</a>
 </h4>
 <p class="sans bold">
 Mary McCoy
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=ya">YA</a>
  /
 <a href="/search?book_genre=ya_fiction">YA Fiction</a>
 </p>
 <p class="excerpt">
 </p><p>With her parents’ looming divorce echoing her own fractured love story, Lee can’t help but wonder whether falling in love is ever worth the risk of falling out of it. Could a series of mysterious objects Lee discovers in her parents’ study hold the answer?</p>
 <div class="read-full">
 <a href="/reviews/26324-mary-mccoy-indestructible-object-ya">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26304-clint-smith-how-word-passed-nonfiction"> <span style="font-style:normal;">★ </span>How the Word Is Passed</a>
 </h4>
 <p class="sans bold">
 Clint Smith
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=nonfiction">Nonfiction</a>
  /
 <a href="/search?book_genre=american_history">American History</a>
  /
 <a href="/search?book_genre=african_american_history">African American History</a>
 </p>
 <p class="excerpt">
 Clint Smith's gifts as both a poet and a scholar make <strong>How the Word Is Passed </strong>a richly provocative read.
 </p>
 <div class="read-full">
 <a href="/reviews/26304-clint-smith-how-word-passed-nonfiction">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26320-tia-williams-seven-days-june-romance"> <span style="font-style:normal;">★ </span>Seven Days in June</a>
 </h4>
 <p class="sans bold">
 Tia Williams
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=romance">Romance</a>
  /
 <a href="/search?book_genre=contemporary_romance">Contemporary Romance</a>
 </p>
 <p class="excerpt">
 Readers will feel as attached to Tia Williams’ characters as Eva and Shane are to each other.
 </p>
 <div class="read-full">
 <a href="/reviews/26320-tia-williams-seven-days-june-romance">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26292-zakiya-dalila-harris-other-black-girl-fiction"> <span style="font-style:normal;">★ </span>The Other Black Girl</a>
 </h4>
 <p class="sans bold">
 Zakiya Dalila Harris
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=literary_fiction">Literary Fiction</a>
 </p>
 <p class="excerpt">
 Brilliantly positioned at the intersection of satire and social horror, Zakiya Dalila Harris’ debut novel is a genre-bending creative triumph.
 </p>
 <div class="read-full">
 <a href="/reviews/26292-zakiya-dalila-harris-other-black-girl-fiction">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26294-nana-nkweti-walking-cowrie-shells-fiction"> <span style="font-style:normal;">★ </span>Walking on Cowrie Shells</a>
 </h4>
 <p class="sans bold">
 Nana Nkweti
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=short_stories">Short Stories</a>
 </p>
 <p class="excerpt">
 With the ease of a master, Nana Nkweti shifts between points of view, between American and African slang, and between the straightforward and the avant-garde.
 </p>
 <div class="read-full">
 <a href="/reviews/26294-nana-nkweti-walking-cowrie-shells-fiction">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26284-taylor-jenkins-reid-malibu-rising-fiction">Malibu Rising</a>
 </h4>
 <p class="sans bold">
 Taylor Jenkins Reid
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=popular_fiction">Popular Fiction</a>
 </p>
 <p class="excerpt">
 <strong>Malibu Rising</strong> is packed with plenty of scintillating scandal, but Taylor Jenkins Reid’s irresistible characters are the novel’s greatest success.
 </p>
 <div class="read-full">
 <a href="/reviews/26284-taylor-jenkins-reid-malibu-rising-fiction">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26356-jules-machias-both-can-be-true-childrens">Both Can Be True</a>
 </h4>
 <p class="sans bold">
 Jules Machias
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=children_s">Children's</a>
  /
 <a href="/search?book_genre=middle_grade">Middle Grade</a>
 </p>
 <p class="excerpt">
 </p><p>“We’re all in the same boat, paddling through the chaos of seventh grade. Except everyone else’s oar is pink or blue and mine’s purple with glittery flecks of angsty confusion on it,” says Ash, who isn’t like most kids in their suburban Ohio middle school.</p>
 <div class="read-full">
 <a href="/reviews/26356-jules-machias-both-can-be-true-childrens">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26291-marianne-cronin-one-hundred-years-lenni-margot-fiction"> <span style="font-style:normal;">★ </span>The One Hundred Years of Lenni and Margot</a>
 </h4>
 <p class="sans bold">
 Marianne Cronin
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=fiction">Fiction</a>
  /
 <a href="/search?book_genre=popular_fiction">Popular Fiction</a>
 </p>
 <p class="excerpt">
 Even in the face of death’s inevitability, friendship can be found, forgiveness can flourish and fun can ease fear.
 </p>
 <div class="read-full">
 <a href="/reviews/26291-marianne-cronin-one-hundred-years-lenni-margot-fiction">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26328-rachel-lynn-solomon-we-cant-keep-meeting-like-this-ya">We Can’t Keep Meeting Like This</a>
 </h4>
 <p class="sans bold">
 Rachel Lynn Solomon
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=ya">YA</a>
  /
 <a href="/search?book_genre=ya_fiction">YA Fiction</a>
 </p>
 <p class="excerpt">
 </p><p>Though Quinn dutifully plays the harp for her family's wedding-planning business, Borrowed + Blue, she doesn't believe in romance anymore, especially not the kind that starts with grand gestures and always ends in heartbreak.</p>
 <div class="read-full">
 <a href="/reviews/26328-rachel-lynn-solomon-we-cant-keep-meeting-like-this-ya">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>,
 <div class="flex-article-content">
 <h4 class="italic">
 <a href="/reviews/26313-elizabeth-letts-ride-her-life-biography"> <span style="font-style:normal;">★ </span>The Ride of Her Life</a>
 </h4>
 <p class="sans bold">
 Elizabeth Letts
 </p>
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=nonfiction">Nonfiction</a>
  /
 <a href="/search?book_genre=biography">Biography</a>
  /
 <a href="/search?book_genre=animals">Animals</a>
 </p>
 <p class="excerpt">
 This is a feel-good story in every way, and Elizabeth Letts keeps the momentum lively, sprinkling in interesting historical tidbits that enrich the drama.
 </p>
 <div class="read-full">
 <a href="/reviews/26313-elizabeth-letts-ride-her-life-nonfiction">Read the Review <i class="zmdi zmdi-chevron-right"></i></a>
 </div>
 </div>]

#### Observations:
    - As Reviews_book for each Book Section does belong to one Common Html Tag. Some Review belong to <p></p> and some belong to <p class='excerpt></p>
    - So we need to make a customize code for extracting both type of TAGS.

In [284]:
reviews_books = []

for i in range(0,5):
    
    if(len(reviews[i].find_all('p'))==3):
        for j in reviews[i].find_all('p',class_='excerpt'):
            reviews_books.append(j.text.replace('\n',''))
    else:
         
        if(len(reviews[i].find_all('p'))==4):
            c = 0
            for j in reviews[i].find_all('p'):
                c=c+1
                if(c==4):
                     reviews_books.append(j.text.replace('\n',''))

In [285]:
reviews_books

['With her parents’ looming divorce echoing her own fractured love story, Lee can’t help but wonder whether falling in love is ever worth the risk of falling out of it. Could a series of mysterious objects Lee discovers in her parents’ study hold the answer?',
 "Clint Smith's gifts as both a poet and a scholar make How the Word Is Passed a richly provocative read.",
 'Readers will feel as attached to Tia Williams’ characters as Eva and Shane are to each other.',
 'Brilliantly positioned at the intersection of satire and social horror, Zakiya Dalila Harris’ debut novel is a genre-bending creative triumph.',
 'With the ease of a master, Nana Nkweti shifts between points of view, between American and African slang, and between the straightforward and the avant-garde.']

In [286]:
books_dict = {
    'Book Name' : book_names,  'Author Name': authors, 'Genres': genres_names, 'Review': reviews_books
    
}

In [287]:
book_Table = pd.DataFrame(books_dict)

In [288]:
book_Table

,Book Name,Author Name,Genres,Review
0,Indestructible Object,Mary McCoy,YA / YA Fiction,With her parents’ looming divorce echoing her ...
1,How the Word Is Passed,Clint Smith,Nonfiction / American History / African Americ...,Clint Smith's gifts as both a poet and a schol...
2,Seven Days in June,Tia Williams,Romance / Contemporary Romance,Readers will feel as attached to Tia Williams’...
3,The Other Black Girl,Zakiya Dalila Harris,Fiction / Literary Fiction,Brilliantly positioned at the intersection of ...
4,Walking on Cowrie Shells,Nana Nkweti,Fiction / Short Stories,"With the ease of a master, Nana Nkweti shifts ..."

In [289]:
book_Table.set_index('Book Name')

,Author Name,Genres,Review
Book Name,,,
Indestructible Object,Mary McCoy,YA / YA Fiction,With her parents’ looming divorce echoing her ...
How the Word Is Passed,Clint Smith,Nonfiction / American History / African Americ...,Clint Smith's gifts as both a poet and a schol...
Seven Days in June,Tia Williams,Romance / Contemporary Romance,Readers will feel as attached to Tia Williams’...
The Other Black Girl,Zakiya Dalila Harris,Fiction / Literary Fiction,Brilliantly positioned at the intersection of ...
Walking on Cowrie Shells,Nana Nkweti,Fiction / Short Stories,"With the ease of a master, Nana Nkweti shifts ..."

## 5. Write a python program to scrape cricket rankings from ‘www.icc-cricket.com’. You have to scrape:
        i) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
        ii) Top 10 ODI Batsmen in men along with the records of their team and rating.
        iii) Top 10 ODI bowlers along with the records of their team and rating

In [290]:
request_odi_men = requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')

In [291]:
request_odi_men

In [292]:
soup_odi_men = BeautifulSoup(request_odi_men.content)

In [293]:
teams = soup_odi_men.find_all('td',class_='table-body__cell rankings-table__team')
matches_points = soup_odi_men.find_all('td',class_='table-body__cell u-center-text')

rating = soup_odi_men.find_all('td',class_='table-body__cell u-text-right rating')

In [294]:
teams

[<td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo AUS"></span>
 <span class="u-hide-phablet">Australia</span>
 <span class="u-show-phablet">AUS</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo IND"></span>
 <span class="u-hide-phablet">India</span>
 <span class="u-show-phablet">IND</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo ENG"></span>
 <span class="u-hide-phablet">England</span>
 <span class="u-show-phablet">ENG</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo SA"></span>
 <span class="u-hide-phablet">South Africa</span>
 <span class="u-show-phablet">SA</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo PAK"></span>
 <span class="u-hide-phablet">Pakistan</span>
 <span class="u-show-phablet">PAK</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo BAN"></span>
 <span class="u-hide-phablet">Bangladesh</span>
 <span class="u-show-phablet">BAN</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo WI"></span>
 <span class="u-hide-phablet">West Indies</span>
 <span class="u-show-phablet">WI</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo SL"></span>
 <span class="u-hide-phablet">Sri Lanka</span>
 <span class="u-show-phablet">SL</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo AFG"></span>
 <span class="u-hide-phablet">Afghanistan</span>
 <span class="u-show-phablet">AFG</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo NED"></span>
 <span class="u-hide-phablet">Netherlands</span>
 <span class="u-show-phablet">NED</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo IRE"></span>
 <span class="u-hide-phablet">Ireland</span>
 <span class="u-show-phablet">IRE</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo ZIM"></span>
 <span class="u-hide-phablet">Zimbabwe</span>
 <span class="u-show-phablet">ZIM</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo SCO"></span>
 <span class="u-hide-phablet">Scotland</span>
 <span class="u-show-phablet">SCO</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo OMA"></span>
 <span class="u-hide-phablet">Oman</span>
 <span class="u-show-phablet">OMA</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo NEP"></span>
 <span class="u-hide-phablet">Nepal</span>
 <span class="u-show-phablet">NEP</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo UAE"></span>
 <span class="u-hide-phablet">UAE</span>
 <span class="u-show-phablet">UAE</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo NAM"></span>
 <span class="u-hide-phablet">Namibia</span>
 <span class="u-show-phablet">NAM</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo USA"></span>
 <span class="u-hide-phablet">United States</span>
 <span class="u-show-phablet">USA</span>
 </td>,
 <td class="table-body__cell rankings-table__team">
 <span class="flag-15 table-body_logo PNG"></span>
 <span class="u-hide-phablet">Papua New Guinea</span>
 <span class="u-show-phablet">PNG</span>
 </td>]

In [295]:
odi_teams_men = []
for i in teams[:9]:
    for j in i.find('span',class_='u-hide-phablet'):
        odi_teams_men.append(j)

In [296]:
matches_points

[<td class="table-body__cell u-center-text">25</td>,
 <td class="table-body__cell u-center-text">2,945</td>,
 <td class="table-body__cell u-center-text">29</td>,
 <td class="table-body__cell u-center-text">3,344</td>,
 <td class="table-body__cell u-center-text">27</td>,
 <td class="table-body__cell u-center-text">3,100</td>,
 <td class="table-body__cell u-center-text">20</td>,
 <td class="table-body__cell u-center-text">2,137</td>,
 <td class="table-body__cell u-center-text">24</td>,
 <td class="table-body__cell u-center-text">2,323</td>,
 <td class="table-body__cell u-center-text">27</td>,
 <td class="table-body__cell u-center-text">2,438</td>,
 <td class="table-body__cell u-center-text">27</td>,
 <td class="table-body__cell u-center-text">2,222</td>,
 <td class="table-body__cell u-center-text">24</td>,
 <td class="table-body__cell u-center-text">1,876</td>,
 <td class="table-body__cell u-center-text">17</td>,
 <td class="table-body__cell u-center-text">1,054</td>,
 <td class="table-body__cell u-center-text">5</td>,
 <td class="table-body__cell u-center-text">249</td>,
 <td class="table-body__cell u-center-text">19</td>,
 <td class="table-body__cell u-center-text">807</td>,
 <td class="table-body__cell u-center-text">15</td>,
 <td class="table-body__cell u-center-text">588</td>,
 <td class="table-body__cell u-center-text">7</td>,
 <td class="table-body__cell u-center-text">258</td>,
 <td class="table-body__cell u-center-text">7</td>,
 <td class="table-body__cell u-center-text">240</td>,
 <td class="table-body__cell u-center-text">5</td>,
 <td class="table-body__cell u-center-text">119</td>,
 <td class="table-body__cell u-center-text">9</td>,
 <td class="table-body__cell u-center-text">190</td>,
 <td class="table-body__cell u-center-text">6</td>,
 <td class="table-body__cell u-center-text">97</td>,
 <td class="table-body__cell u-center-text">8</td>,
 <td class="table-body__cell u-center-text">93</td>,
 <td class="table-body__cell u-center-text">5</td>,
 <td class="table-body__cell u-center-text">0</td>]

#### OBSERVATIONS:
        - Every Odd Places is for no of matches and even places for Points

In [297]:
points = []
matches = []
c = 0
for i in matches_points[:18]:
    if(c%2==0):
        matches.append(i.text)
    else:
        points.append(i.text)
    c = c+1

In [298]:
team_rating = []
for i in rating[:9]:
    team_rating.append(i.text)

In [299]:
team_rating

['118', '115', '115', '107', '97', '90', '82', '78', '62']

### EXTRACTING THE TOP 1 DETAILS AS ITS HTML TAGS ARE DIFFERENT THAN OTHER TEAMS.

In [300]:
top_match = soup_odi_men.find('td',class_='rankings-block__banner--matches')
top_point= soup_odi_men.find('td',class_='rankings-block__banner--points')
top_rating = soup_odi_men.find('td',class_='rankings-block__banner--rating u-text-right')
top_team = soup_odi_men.find('span','u-hide-phablet')

In [301]:
top_team

In [302]:
odi_teams_men.append(top_team.text)

In [303]:
top_match.text,top_point.text,top_rating.text.replace('\n','')

('17', '2,054', '                            121                            ')

In [304]:
final_rating = top_rating.text.replace('\n','')

In [305]:
points.append(top_point.text)

In [306]:
matches.append(top_match.text)

In [307]:
team_rating.append(final_rating.replace(' ',''))

In [308]:
odi_team_top_dict = {
    'TEAM NAME': odi_teams_men, 'POINTS': points,'MATCHES':matches,'RATING': team_rating
}

In [309]:
men_odi_table = pd.DataFrame(odi_team_top_dict)

In [310]:
men_odi_table['POINTS'] = men_odi_table['POINTS'].apply(lambda x: x.replace(',',''))

In [311]:
men_odi_table['RATING']=men_odi_table['RATING'].astype('int32')
men_odi_table['POINTS']=men_odi_table['POINTS'].astype('int32')
men_odi_table['MATCHES']=men_odi_table['MATCHES'].astype('int32')

In [312]:
table_men_odi = men_odi_table.sort_values(by=['RATING'],ascending=False)

In [313]:
table_men_odi.set_index('TEAM NAME')

              POINTS  MATCHES  RATING
TEAM NAME
New Zealand     2054       17     121
Australia       2945       25     118
India           3344       29     115
England         3100       27     115
South Africa    2137       20     107
Pakistan        2323       24      97
Bangladesh      2438       27      90
West Indies     2222       27      82
Sri Lanka       1876       24      78
Afghanistan     1054       17      62

### ii) Top 10 ODI Batsmen in men along with the records of their team and rating.

In [314]:
re1 = requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi')

In [315]:
soup_batsmen = BeautifulSoup(re1.content)

In [316]:
player = soup_batsmen.find_all('td',class_='table-body__cell name')
team  =  soup_batsmen.find_all('span',class_='table-body__logo-text')
pl_rating =  soup_batsmen.find_all('td',class_='table-body__cell u-text-right rating')

In [317]:
players = []
for i in player[:9]:
    for j in i.find('a'):
        players.append(j)


teams_batsmen = []
pl_batsmen_rating=[]

for i in team[:9]:
    teams_batsmen.append(i.text)
        
        
for i in pl_rating[:9]:
    pl_batsmen_rating.append(i.text)

In [318]:
players,teams_batsmen,pl_batsmen_rating

(['Virat Kohli',
  'Rohit Sharma',
  'Ross Taylor',
  'Aaron Finch',
  'Jonny Bairstow',
  'Fakhar Zaman',
  'Francois du Plessis',
  'David Warner',
  'Shai Hope'],
 ['IND', 'IND', 'NZ', 'AUS', 'ENG', 'PAK', 'SA', 'AUS', 'WI'],
 ['857', '825', '801', '791', '785', '778', '778', '773', '773'])

### EXTRACTING THE DETAILS FOR 1st Top BATSMEN

In [319]:
top_player_btm= soup_batsmen.find('div',class_='rankings-block__banner--name')
top_team_btm= soup_batsmen.find('div',class_='rankings-block__banner--nationality')
top_rating_btm = soup_batsmen.find('div',class_='rankings-block__banner--rating')

In [320]:
top_player_btm,top_rating_btm,top_team_btm.text

(<div class="rankings-block__banner--name">Babar Azam</div>,
 <div class="rankings-block__banner--rating">865</div>,
 '\n\nPAK\n                            865\n')

In [321]:
top_team_btm

<div class="rankings-block__banner--nationality">
<div class="flag-15 PAK"></div>
<span class="rankings-block__banner--nation"></span>PAK
                            <div class="rankings-block__banner--rating">865</div>
</div>

In [322]:
count = 0 
country = ''
for i in top_team_btm:
    count = count+1
    if(count==5):
        country=i

In [323]:
pakistan = country.replace('\n','')

In [324]:
teams_batsmen.append(pakistan.replace(' ',''))

In [325]:
pl_batsmen_rating.append(top_rating_btm.text)
players.append(top_player_btm.text)

In [326]:
teams_batsmen

['IND', 'IND', 'NZ', 'AUS', 'ENG', 'PAK', 'SA', 'AUS', 'WI', 'PAK']

In [327]:
odi_men_bats_dict = {
    'Team': teams_batsmen, 'Player': players, 'Rating': pl_batsmen_rating
}

In [328]:
men_odi_btm_table = pd.DataFrame(odi_men_bats_dict
                                )

In [329]:
 men_odi_btm_table['Rating'] = men_odi_btm_table['Rating'].astype('int')

In [330]:
btm_men_odi_Team = men_odi_btm_table.sort_values(by=['Rating'],ascending=False)

In [331]:
btm_men_odi_Team

  Team               Player  Rating
9  PAK           Babar Azam     865
0  IND          Virat Kohli     857
1  IND         Rohit Sharma     825
2   NZ          Ross Taylor     801
3  AUS          Aaron Finch     791
4  ENG       Jonny Bairstow     785
5  PAK         Fakhar Zaman     778
6   SA  Francois du Plessis     778
7  AUS         David Warner     773
8   WI            Shai Hope     773

### iii) Top 10 ODI bowlers along with the records of their team and rating

In [332]:
player = soup_batsmen.find_all('td',class_='table-body__cell name')
team  =  soup_batsmen.find_all('span',class_='table-body__logo-text')
pl_rating =  soup_batsmen.find_all('td',class_='table-body__cell u-text-right rating')

In [333]:
bowlers = []
for i in player[9:18]:
    for j in i.find('a'):
        bowlers.append(j)


teams_bowler = []


for i in team[9:18]:
    teams_bowler.append(i.text)

bowler_rating  =[]    
        
for i in pl_rating[9:18]:
    bowler_rating.append(i.text)

In [334]:
bowlers, bowler_rating,teams_bowler

(['Mehedi Hasan',
  'Mujeeb Ur Rahman',
  'Matt Henry',
  'Jasprit Bumrah',
  'Kagiso Rabada',
  'Chris Woakes',
  'Josh Hazlewood',
  'Pat Cummins',
  'Mustafizur Rahman'],
 ['713', '708', '691', '690', '666', '665', '660', '646', '645'],
 ['BAN', 'AFG', 'NZ', 'IND', 'SA', 'ENG', 'AUS', 'AUS', 'BAN'])

In [335]:
top_player_bowl = soup_batsmen.find_all('div',class_='rankings-block__banner--name')
top_team_bowl = soup_batsmen.find_all('div',class_='rankings-block__banner--nationality')
top_rating_bowl = soup_batsmen.find_all('div',class_='rankings-block__banner--rating')

In [336]:
text_count = ''

for i in top_team_bowl[1:2]:
    text_count = i.text.replace(' ','')

In [337]:
text = text_count.split('\n')

In [338]:
while("" in text) :
    text.remove("")

In [339]:
text

['NZ', '737']

In [340]:
country = text[0]

In [341]:
country

'NZ'

In [342]:
teams_bowler.append(country)

In [343]:
teams_bowler

['BAN', 'AFG', 'NZ', 'IND', 'SA', 'ENG', 'AUS', 'AUS', 'BAN', 'NZ']

In [344]:

bowlers.append( top_player_bowl[1].text)

In [345]:
bowler_rating.append(top_rating_bowl[1].text)

In [346]:
odi_men_bowl_dict = {
    'Team': teams_bowler, 'Player': bowlers, 'Rating': bowler_rating
}

In [347]:
men_odi_bowl_table = pd.DataFrame(odi_men_bowl_dict
                                )

In [348]:
btm_men_bowl_Team = men_odi_bowl_table.sort_values(by=['Rating'],ascending=False)

In [349]:
btm_men_bowl_Team

  Team             Player Rating
9   NZ        Trent Boult    737
0  BAN       Mehedi Hasan    713
1  AFG   Mujeeb Ur Rahman    708
2   NZ         Matt Henry    691
3  IND     Jasprit Bumrah    690
4   SA      Kagiso Rabada    666
5  ENG       Chris Woakes    665
6  AUS     Josh Hazlewood    660
7  AUS        Pat Cummins    646
8  BAN  Mustafizur Rahman    645

## 6. Write a python program to scrape cricket rankings from ‘www.icc-cricket.com’. You have to scrape:
    i) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.
    ii) Top 10 women’s ODI players along with the records of their team and rating.
    iii) Top 10 women’s ODI all-rounder along with the records of their team and rating.

In [350]:
women_url = requests.get('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')
women_url

In [351]:
soup = BeautifulSoup(women_url.content)

In [352]:
teams = soup.find_all('td',class_='table-body__cell rankings-table__team')
matches_points = soup.find_all('td',class_='table-body__cell u-center-text')

rating_teams = soup.find_all('td',class_='table-body__cell u-text-right rating')

In [353]:
odi_teams_wm = []
for i in teams[:9]:
    for j in i.find('span',class_='u-hide-phablet'):
        odi_teams_wm.append(j)

        
points = []
matches = []
c = 0
for i in matches_points[:18]:
    if(c%2==0):
        matches.append(i.text)
    else:
        points.append(i.text.replace(',',''))
    c = c+1

    
team_rating = []
for i in rating_teams[:9]:
    team_rating.append(i.text)

In [354]:
odi_teams_wm,points,matches,team_rating

(['South Africa',
  'England',
  'India',
  'New Zealand',
  'West Indies',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Ireland'],
 ['2828', '1993', '2226', '1947', '1025', '1101', '306', '519', '25'],
 ['24', '17', '20', '21', '12', '15', '5', '11', '2'],
 ['118', '117', '111', '93', '85', '73', '61', '47', '13'])

### EXTRACTING TOP DETAILS OF ODI 1st  NUMBER TEAM

In [355]:
top_match = soup.find('td',class_='rankings-block__banner--matches')
top_point= soup.find('td',class_='rankings-block__banner--points')
top_rating = soup.find('td',class_='rankings-block__banner--rating u-text-right')

In [356]:
top_match,top_point,top_rating

(<td class="rankings-block__banner--matches">18</td>,
 <td class="rankings-block__banner--points">2,955</td>,
 <td class="rankings-block__banner--rating u-text-right">
                             164
                             <span class="circle-branding circle-branding--top"></span>
 <span class="circle-branding circle-branding--bottom"></span>
 </td>)

In [357]:
top_team = soup.find('span','u-hide-phablet')

In [358]:
odi_teams_wm.append(top_team.text)

In [359]:
final_rating = top_rating.text.replace('\n','')
points.append(top_point.text.replace(',',''))
matches.append(top_match.text)
team_rating.append(final_rating.replace(' ',''))

In [360]:
odi_team_top_dict = {
    'TEAM NAME': odi_teams_wm, 'POINTS': points,'MATCHES':matches,'RATING': team_rating
}

In [361]:
women_odi_table = pd.DataFrame(odi_team_top_dict)

In [362]:
women_odi_table['RATING']=women_odi_table['RATING'].astype('int32')
women_odi_table['POINTS']=women_odi_table['POINTS'].astype('int32')
women_odi_table['MATCHES']=women_odi_table['MATCHES'].astype('int32')
table_women_odi = women_odi_table.sort_values(by=['RATING'],ascending=False).reset_index()

In [363]:
table_women_odi.drop('index',inplace=True,axis=1)

In [364]:
table_women_odi

      TEAM NAME  POINTS  MATCHES  RATING
0     Australia    2955       18     164
1  South Africa    2828       24     118
2       England    1993       17     117
3         India    2226       20     111
4   New Zealand    1947       21      93
5   West Indies    1025       12      85
6      Pakistan    1101       15      73
7    Bangladesh     306        5      61
8     Sri Lanka     519       11      47
9       Ireland      25        2      13

## ii) Top 10 women’s ODI players along with the records of their team and rating.

In [365]:
url_women1 = requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi')
url_women1

In [366]:
soup1 = BeautifulSoup(url_women1.content)
players = soup1.find_all('td',class_='table-body__cell name')
teams = soup1.find_all('span',class_='table-body__logo-text')
rating_players  = soup1.find_all('td','table-body__cell u-text-right rating')

In [367]:
pls = []
for i in players[:9]:
    for j in i.find('a'):
        pls.append(j)


teams_batsmen = []
pl_batsmen_rating=[]

for i in teams[:9]:
    teams_batsmen.append(i.text)
        
        
for i in rating_players[:9]:
    pl_batsmen_rating.append(i.text)

#### EXTRACTING DETAILS OF top 1 banner player

In [368]:
top_player_btm= soup1.find('div',class_='rankings-block__banner--name')
top_team_btm= soup1.find('div',class_='rankings-block__banner--nationality')
top_rating_btm = soup1.find('div',class_='rankings-block__banner--rating')

In [369]:
top_player_btm,top_rating_btm,top_team_btm

(<div class="rankings-block__banner--name">Tammy Beaumont</div>,
 <div class="rankings-block__banner--rating">765</div>,
 <div class="rankings-block__banner--nationality">
 <div class="flag-15 ENG"></div>
 <span class="rankings-block__banner--nation"></span>ENG
                             <div class="rankings-block__banner--rating">765</div>
 </div>)

In [370]:
count = 0 
country = ''
for i in top_team_btm:
    count = count+1
    if(count==5):
        country=i
        
top_tn = country.replace('\n','')
teams_batsmen.append(top_tn.replace(' ',''))
pl_batsmen_rating.append(top_rating_btm.text)
pls.append(top_player_btm.text)

In [371]:
odi_women_bats_dict = {
    'Team': teams_batsmen, 'Player': pls, 'Rating': pl_batsmen_rating
}
women_odi_btm_table = pd.DataFrame(odi_women_bats_dict
                                )

In [372]:
 women_odi_btm_table['Rating'] = women_odi_btm_table['Rating'].astype('int')

In [373]:
women_odi_btm_table = women_odi_btm_table.sort_values(by=['Rating'],ascending=False)
table = women_odi_btm_table.reset_index()

In [374]:
table.drop('index',axis=1,
           inplace=True)

In [375]:
table

  Team             Player  Rating
0  ENG     Tammy Beaumont     765
1   SA        Lizelle Lee     758
2  AUS       Alyssa Healy     756
3   WI    Stafanie Taylor     746
4  AUS        Meg Lanning     723
5   NZ  Amy Satterthwaite     715
6  IND    Smriti Mandhana     710
7  IND        Mithali Raj     709
8  ENG     Natalie Sciver     685
9   SA    Laura Wolvaardt     683

## iii) Top 10 women’s ODI all-rounder along with the records of their team and rating.

In [376]:
players_all_rounder = []
for i in players[18:]:
    for j in i.find('a'):
        players_all_rounder.append(j)

In [377]:
players_all_rounder

['Ellyse Perry',
 'Stafanie Taylor',
 'Natalie Sciver',
 'Deepti Sharma',
 'Jess Jonassen',
 'Ashleigh Gardner',
 'Dane van Niekerk',
 'Sophie Devine',
 'Amelia Kerr']

In [378]:
teams_allRounder = []
rating_all_rounder=[]

for i in teams[18:]:
    teams_allRounder.append(i.text)
        
        
for i in rating_players[18:]:
    rating_all_rounder.append(i.text)

teams_allRounder

['AUS', 'WI', 'ENG', 'IND', 'AUS', 'AUS', 'SA', 'NZ', 'NZ']

In [379]:
### EXtracting information of 1st player

top_player_ar= soup1.find_all('div',class_='rankings-block__banner--name')
top_team_ar= soup1.find_all('div',class_='rankings-block__banner--nationality')
top_rating_ar = soup1.find_all('div',class_='rankings-block__banner--rating')

top_player_ar,top_rating_ar,top_team_ar

([<div class="rankings-block__banner--name">Tammy Beaumont</div>,
  <div class="rankings-block__banner--name">Jess Jonassen</div>,
  <div class="rankings-block__banner--name">Marizanne Kapp</div>],
 [<div class="rankings-block__banner--rating">765</div>,
  <div class="rankings-block__banner--rating">808</div>,
  <div class="rankings-block__banner--rating">418</div>],
 [<div class="rankings-block__banner--nationality">
  <div class="flag-15 ENG"></div>
  <span class="rankings-block__banner--nation"></span>ENG
                              <div class="rankings-block__banner--rating">765</div>
  </div>,
  <div class="rankings-block__banner--nationality">
  <div class="flag-15 AUS"></div>
  <span class="rankings-block__banner--nation"></span>AUS
                              <div class="rankings-block__banner--rating">808</div>
  </div>,
  <div class="rankings-block__banner--nationality">
  <div class="flag-15 SA"></div>
  <span class="rankings-block__banner--nation"></span>SA
                              <div class="rankings-block__banner--rating">418</div>
  </div>])

In [380]:
players_all_rounder.append(top_player_ar[-1].text)

rating_all_rounder.append(top_rating_ar[-1].text)

count = 0 
cont = ''
for i in top_team_ar[-1]:
    count = count+1
    if(count==5):
        cont =i

top_tn = cont.replace('\n','')
teams_allRounder.append(top_tn.replace(' ',''))


teams_allRounder

['AUS', 'WI', 'ENG', 'IND', 'AUS', 'AUS', 'SA', 'NZ', 'NZ', 'SA']

In [381]:
odi_women_ar_dict = {
    'Team': teams_allRounder, 'Player': players_all_rounder, 'Rating': rating_all_rounder
}
women_odi_btm_table = pd.DataFrame(odi_women_ar_dict
                                )

women_odi_btm_table['Rating'] = women_odi_btm_table['Rating'].astype('int')

all_rounder_table = women_odi_btm_table.sort_values(by=['Rating'],ascending=False)

table_ar = all_rounder_table.reset_index()

table_ar.drop('index',axis=1,
           inplace=True)

table_ar

  Team            Player  Rating
0  AUS      Ellyse Perry     418
1   SA    Marizanne Kapp     418
2   WI   Stafanie Taylor     410
3  ENG    Natalie Sciver     349
4  IND     Deepti Sharma     343
5  AUS     Jess Jonassen     307
6  AUS  Ashleigh Gardner     252
7   SA  Dane van Niekerk     243
8   NZ     Sophie Devine     242
9   NZ       Amelia Kerr     236

# 7. Write a python program to scrape details of all the mobile phones under Rs. 20,000 listed on Amazon.in. The 
    scraped data should include Product Name, Price, Image URL and Average Rating

In [382]:
amazon = requests.get('https://www.amazon.in/s?k=mobile+phones+below+20000+rupees&crid=240QRL91TRR9N&sprefix=mobile+phones+below+20000%2Caps%2C340&ref=nb_sb_ss_ts-doa-p_1_25')
amazon

In [383]:

soup = BeautifulSoup(amazon.content)

mobile_sections = soup.find_all('div',class_='a-section a-spacing-medium')

mobile_sections

[]

In [384]:
products = []
urls = []
prices = []
rating = []

for i in mobile_sections:
    
    for j in i.find('div',class_='a-section aok-relative s-image-fixed-height'):
        urls.append(j.get('src'))
      
    
    for k in i.find('span',class_='a-icon-alt'):
        l =[]
        l = k.split(' ')
        rating.append(l[0])
    for l in i.find('span',class_='a-price-whole'):
        prices.append(l.replace(',',''))
    for n in i.find('span',class_='a-size-medium a-color-base a-text-normal'):
        l = []
        l = n.split('|')
        if ('with' in l[0]):
            l1 = []
            l1 = l[0].split('with')
            products.append(l1[0])
        else:
            products.append(l[0])

mobile_dict = {
    'ProductName': products,
    'Price': prices,
    'Rating': rating,
    'Image Url': urls
}

mobiles = pd.DataFrame(mobile_dict)

mobiles

Empty DataFrame
Columns: [ProductName, Price, Rating, Image Url]
Index: []

## 8. Write a python program to extract information about the local weather from the National Weather Service 
website of USA, https://www.weather.gov/ for the city, San Francisco. You need to extract data about 7 day 
extended forecast display for the city. The data should include period, short description, temperature and 
description.

In [385]:
weather = requests.get('https://forecast.weather.gov/MapClick.php?lat=37.777120000000025&lon=-122.41963999999996#.YLh566gzZPY')
weather

In [386]:
soup1 = BeautifulSoup(weather.content)

days = soup1.find_all('div',class_='col-sm-2 forecast-label')
texts = soup1.find_all('div',class_='col-sm-10 forecast-text')

In [387]:
ex_days = []
for i in days:
    ex_days.append(i.text)

In [388]:
desc = []
text = []
short_description = []
for i in texts:
    text.append(i.text)
    li = []
    li =i.text.replace(',','.').split('with',1)
    short_description.append(li[0])
    desc.append(li[1])

descriptions= []
for i in desc:
    descriptions.append(i.replace('near','around'))

In [389]:
tempretures = []
for i in descriptions:
    l =[]
    l =i.replace('.','').split(' ')
    count = 1
    for i in l:
        
        if(i.isdigit()):
           
            if(count == 1):
                 tempretures.append(i)
            count=count+1

In [390]:
dic_weather = {
    'Day': ex_days,
    'Short Description': short_description,
    'Tempreture (F)': tempretures,
    'Description': text
}

weather_table = pd.DataFrame(dic_weather)

weather_table

,Day,Short Description,Tempreture (F),Description
0,Overnight,Mostly cloudy.,54,"Mostly cloudy, with a low around 54. West wind..."
1,Friday,Mostly cloudy. then gradually becoming sunny.,64,"Mostly cloudy, then gradually becoming sunny, ..."
2,Friday Night,Mostly clear.,53,"Mostly clear, with a low around 53. Breezy, wi..."
3,Saturday,Sunny.,69,"Sunny, with a high near 69. West wind 6 to 11 ..."
4,Saturday Night,Mostly clear.,52,"Mostly clear, with a low around 52. Breezy, wi..."
5,Sunday,Sunny.,68,"Sunny, with a high near 68."
6,Sunday Night,Mostly clear.,52,"Mostly clear, with a low around 52."
7,Monday,Sunny.,65,"Sunny, with a high near 65."
8,Monday Night,Mostly clear.,51,"Mostly clear, with a low around 51."
9,Tuesday,Sunny.,64,"Sunny, with a high near 64."
10,Tuesday Night,Mostly clear.,50,"Mostly clear, with a low around 50."
11,Wednesday,Sunny.,65,"Sunny, with a high near 65."
12,Wednesday Night,Mostly clear.,51,"Mostly clear, with a low around 51."
13,Thursday,Sunny.,67,"Sunny, with a high near 67."

## 9. Write a python program to scrape fresher job listings from ‘https://internshala.com/’. 
    It should include job title, company name, CTC, and apply date

In [391]:
job_url = requests.get('https://internshala.com/fresher-jobs')
job_url

In [392]:
soup2 = BeautifulSoup(job_url.content)

In [393]:
job_title = soup2.find_all('div',class_='heading_4_5 profile') 
company_name = soup2.find_all('a',class_='link_display_like_text')  
body = soup2.find_all('div',class_='item_body')

In [394]:
jobs = []
for i in job_title:
    for j in i.find('a'):
        jobs.append(j)

companies = []
for i in company_name:
    text = i.text.replace('\n','')
    companies.append(text.replace(' ',''))

In [395]:
ctc = []
dates = []
count =1
for i in body[1:]:
    
    if(count%3==1):
        text = i.text.replace('\n','')
        ctc.append(text.replace(' ',''))
   
    
    elif(count%3==2):
        
        dates.append(i.text.replace(' ',''))
    
    count = count+1

In [396]:
jobs_dict = {
    'Company_name':companies,
    'Job_Title': jobs,
    'CTC': ctc,
    'Apply Date':dates
    
}

jobs = pd.DataFrame(jobs_dict)

jobs

,Company_name,Job_Title,CTC,Apply Date
0,WollfishLabsPrivateLimited,Backend Developer (Ruby On Rails),6-8LPA,4Jul'21
1,WonoInc,Customer Service Specialist,5.2-6.4LPA,3Jul'21
2,WonoInc,Graphic Designer,5-6.5LPA,3Jul'21
3,WonoInc,Digital Marketing Specialist,5-6.5LPA,3Jul'21
4,Wyntem,Junior Corporate Sales Executive,3-3.5LPA,3Jul'21
5,HomeJam,Backend Developer,7-8.5LPA,3Jul'21
6,NCTILLP,Junior Operations Executive,3-3.6LPA,3Jul'21
7,TranspeninsulaLLC,Internal Audit Associate,4.8-6LPA,3Jul'21
8,MentorBoxx,Business Marketing Manager,4-8.5LPA,3Jul'21
9,RunnersPlanet,React Native Developer,6.62-7.95LPA,3Jul'21
10,"InstituteForGovernance,Policies&Politics",Research And Communications Associate,3-4.5LPA,3Jul'21
11,ProtonAutoML,Data Scientist,3-3.5LPA,2Jul'21
12,Markytics,Data Science Django Developer,3-4.5LPA,2Jul'21
13,MiM-Essay,Corporate Sales Associate,5-6.5LPA,2Jul'21
14,Wondermail,Full Stack Developer,4-7LPA,1Jul'21
15,ProjectTinker,Full Stack Developer (MERN),4-7.2LPA,3Jul'21
16,KaizenAcademy,Business Development Executive,4.5-6LPA,1Jul'21
17,Amigobulls,Sales Development Representative,5.5-6.5LPA,1Jul'21
18,UndergroundMovementLLP,Graphic Designer,3-5LPA,1Jul'21
19,AlphacoreTechnologiesPrivateLimited,Operations Executive,3-3.5LPA,1Jul'21
20,RuhcomEnterprisesPrivateLimited,Business Development Executive,3LPA,1Jul'21
21,SkyEducationGroup,Admission Counselor (Sales),3LPA,30Jun'21
22,Mo'sF&BGroup,Sales And Business Development Analyst,3-3.1LPA,30Jun'21
23,SleepLove,Growth Hacking Digital Marketer,3-3.5LPA,3Jul'21
24,Askadmissions.ai,Junior Node.js Developer,3-4LPA,30Jun'21
25,Krivy,Junior Digital Marketing Executive,3LPA,30Jun'21
26,AscentsparkSoftwarePrivateLimited,iOS App Developer,3.6-7LPA,30Jun'21
27,TruffleNation,Food Journalist,3-4.5LPA,30Jun'21
28,HabitateTechnologiesPrivateLimited,Junior Software Developer,5.2-7LPA,30Jun'21
29,SoluLab,Full Stack Developer,3-5LPA,28Jun'21
30,SoluLab,Business Analyst,3-4.2LPA,28Jun'21
31,REPOZITORYTECHNOLOGIESPRIVATELIMITED,Associate Full Stack Developer,3-3.6LPA,30Jun'21
32,BeehiveAcademyIndia,Full Stack Engineer,4.2-8.2LPA,28Jun'21
33,Bip,Product Marketer,3-6LPA,27Jun'21
34,Tabeazy,Business Development Executive,3LPA,27Jun'21
35,LeverageEdu,Associate - Business Development,3.6LPA,27Jun'21
36,DEX-DEFTResearchAndConsultingOPCPrivateLimited,Research Analyst (Economics),3LPA,3Jul'21
37,AIMonkLabsTechnologyLimited,Machine Learning Engineer,5-6.5LPA,27Jun'21
38,KasperConsultingPrivateLimited,Business Analyst,3.25-4LPA,26Jun'21
39,GREedge,Business Development Executive (Inside Sales),3.75LPA,26Jun'21